Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2019-12, with the labels that each got.

#323 update frontend package and quote colors
  api/lib/config/environments/preview.config.ts
  package-lock.json
  package.json
  src/assets/components/button/_button.scss
  src/assets/components/casefile/_casefile-2.scss
  src/assets/components/casefile/_casefile-3.scss
  src/assets/components/casefile/_casefile.scss
  src/assets/components/header/_header.scss
  src/assets/components/primary-nav/_primary-nav.scss
  src/assets/components/tabs/_tabs.scss
  src/assets/components/tree/_tree.scss
  src/assets/sass/patterns/_pba.scss
  yarn.lock
Labels: ns:xui-mo-webapp-pr-323

#330 Updating app const to add FPLA, IA & SSCS in Demo
  src/app/app.constants.ts
Labels: ns:xui-mo-webapp-pr-330

#324 making the invite user to display the error from server
  api/inviteUser/index.ts
  src/users/containers/invite-user/invite-user.component.ts
  src/users/store/reducers/invite-user.reducer.ts
Labels: CABApproved, ns:xui-mo-webapp-pr-324
