Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2019-08, with the labels that each got.

#144 Feature/fz updating links to external
  api/auth/index.ts
  api/inviteUser/index.ts
  api/lib/config/application.config.ts
  api/lib/interceptors.ts
  api/organisation/index.ts
  api/userList/index.ts
  src/organisation/containers/organisation/organisation.component.html
  src/organisation/containers/organisation/organisation.component.ts
  src/organisation/organisation.model.ts
  src/organisation/store/actions/organisation.actions.spec.ts
  src/organisation/store/reducers/organisation.reducer.ts
  src/organisation/store/selectors/organisation.selectors.ts
  src/user-profile/guards/auth.guard.ts
  src/user-profile/services/user.service.ts
  src/users/components/invite-user-form/invite-user-form.component.html
  src/users/containers/invite-user/invite-user.component.ts
  src/users/store/reducers/users.reducer.ts
Labels: ns:xui-mo-webapp-pr-144

#147 Update README.md title
  README.md
Labels: ns:xui-mo-webapp-pr-147

#149 Feature/eui 526 invite user
  api/jurisdictions/index.ts
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/local.config.ts
  api/lib/config/environments/preview.config.ts
  api/routes.ts
  src/app/app.module.ts
  src/app/store/actions/app.actions.spec.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effects.spec.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app.reducer.spec.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/register/containers/register/register.component.ts
  src/users/containers/invite-user/invite-user.component.ts
  src/users/models/userform.model.ts
  src/users/services/index.ts
  src/users/services/jurisdiction.service.spec.ts
  src/users/services/jurisdiction.service.ts
  src/users/store/effects/invite-user.effects.spec.ts
  src/users/store/effects/invite-user.effects.ts
Labels: ns:xui-mo-webapp-pr-149

#141 Bug/eui 518 logging out aa
  api/server.ts
  src/app/store/effects/app.effects.ts
Labels: ns:xui-mo-webapp-pr-141

#157 Confirmation page extracted and updated
  src/app/utils/app-utils.ts
  src/register/components/submitted-confirmation/submitted-confirmation.component.ts
  src/register/containers/register/register.component.html
  src/register/containers/register/register.component.ts
  src/register/register.routing.ts
Labels: ns:xui-mo-webapp-pr-157

#161 Using constants for Jurisdiction
  src/app/app.constants.ts
  src/register/containers/register/register.component.ts
Labels: ns:xui-mo-webapp-pr-161

#158 setting permission routing
  api/routes.ts
  src/app/app.routes.ts
  src/app/containers/header/header.component.html
  src/app/containers/index.ts
  src/app/containers/redirect/redirect.component.spec.ts
  src/app/containers/redirect/redirect.component.ts
  src/organisation/store/actions/organisation.actions.ts
Labels: ns:xui-mo-webapp-pr-158

#162 EUI-220/EUI-487 Updating error messages
  src/register/mappings/apiErrorMappings.ts
Labels: ns:xui-mo-webapp-pr-162

#163 Reset the next url
  src/register/containers/register/register.component.ts
Labels: ns:xui-mo-webapp-pr-163

#164 Format payload of superUser with Jurisdictions
  api/lib/payloadBuilder.ts
Labels: ns:xui-mo-webapp-pr-164

#165 Bug/eui 549 register validation aa
  api/states/templates/organisationDx.ts
  api/states/templates/organisationHaveDx.ts
  api/states/templates/organisationHaveSra.ts
  src/register/containers/hmcts-form-builder/src/lib/components/radiobutton/radiobutton.component.html
  src/register/store/reducers/registration.reducer.ts
Labels: ns:xui-mo-webapp-pr-165

#166 Feature/eui 538
  package-lock.json
  package.json
  src/app/app.module.ts
  src/fee-accounts/store/effects/single-fee-account.effects.spec.ts
  src/fee-accounts/store/effects/single-fee-account.effects.ts
  src/organisation/organisation.module.ts
  src/organisation/store/effects/organisation.effects.ts
  src/register/containers/register/register.component.ts
  src/register/store/effects/registration.effects.spec.ts
  src/register/store/effects/registration.effects.ts
  src/shared/errorHandler/defaultErrorHandler.spec.ts
  src/shared/errorHandler/defaultErrorHandler.ts
  src/shared/services/CryptoWrapper.spec.ts
  src/shared/services/cryptoWrapper.ts
  src/shared/services/jwtDecodeWrapper.ts
  src/shared/services/logger.service.spec.ts
  src/shared/services/logger.service.ts
  src/users/store/effects/invite-user.effects.spec.ts
  src/users/store/effects/invite-user.effects.ts
  yarn.lock
Labels: ns:xui-mo-webapp-pr-166

#167 Bug/fz phill removing auth for registration
  api/auth/index.ts
  api/lib/s2sTokenGeneration.ts
  api/local.ts
  api/openRoutes.ts
  api/register-org/index.ts
  api/routes.ts
  api/server.ts
  api/services/rdProfessional.ts
  api/services/serviceAuth.ts
  api/states/index.ts
  api/states/mapping.ts
  api/states/templates/emailAddress.ts
  api/states/templates/index.ts
  api/states/templates/name.ts
  api/states/templates/organisationAddress.ts
  api/states/templates/organisationDx.ts
  api/states/templates/organisationHaveSra.ts
  api/states/templates/organisationPba.ts
  api/states/templates/sraNumber.ts
  proxy.config.json
  src/app/containers/app/app.component.scss
  src/app/containers/app/app.component.ts
  src/register/constants/emailAddress.ts
  src/register/constants/haveDx.ts
  src/register/constants/name.ts
  src/register/constants/oganisationName.ts
  src/register/constants/organisationAddress.ts
  src/register/constants/organisationDx.ts
  src/register/constants/organisationHaveSra.ts
  src/register/constants/pbaNumber.ts
  src/register/constants/registration.constants.ts
  src/register/constants/sraNumber.ts
  src/register/register.routing.ts
  src/register/services/registration-form.service.ts
  src/shared/services/headers.service.ts
Labels: ns:xui-mo-webapp-pr-167

#150 back button removed for registration confirmation
  src/register/containers/register/register.component.html
Labels: ns:xui-mo-webapp-pr-150

#168 Chore/eui 560 security vulnerabilities aa
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  api/yarn.lock
  package-lock.json
  package.json
  test/e2e/support/reports.js
  yarn.lock
Labels: ns:xui-mo-webapp-pr-168

#160 reformat dx number and dx exchange display
  src/register/components/check-your-answers/check-your-answers.component.html
Labels: ns:xui-mo-webapp-pr-160

#159 adding the missing , for PBA numbers
  src/register/components/check-your-answers/check-your-answers.component.html
Labels: ns:xui-mo-webapp-pr-159

#137 Feature/fix unit tests
  api/accounts/index.spec.ts
  api/lib/payloadBuilder.spec.ts
Labels: ns:xui-mo-webapp-pr-137

#170 Bug/fixing registration post
  api/lib/config/application.config.ts
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/local.config.ts
  api/lib/payloadBuilder.ts
  api/lib/s2sTokenGeneration.ts
  api/register-org/index.ts
  api/services/rdProfessional.ts
  src/register/store/effects/registration.effects.ts
  src/register/store/reducers/registration.reducer.spec.ts
  src/register/store/reducers/registration.reducer.ts
  src/register/store/selectors/registration.selectors.spec.ts
Labels: ns:xui-mo-webapp-pr-170

#173 Bug/eui 591
  api/openRoutes.ts
  api/routes.ts
  src/register/store/effects/registration.effects.ts
  src/shared/services/logger.service.ts
  src/shared/services/monitoring.service.ts
Labels: ns:xui-mo-webapp-pr-173

#175 adding removed endpoints
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/local.config.ts
Labels: ns:xui-mo-webapp-pr-175

#172 Feature/eui 520
  src/app/containers/app/app.component.ts
  src/assets/sass/application.scss
  src/register/components/check-your-answers/check-your-answers.component.html
  src/register/components/check-your-answers/check-your-answers.component.ts
  src/register/containers/register/register.component.html
  src/register/containers/register/register.component.ts
  src/register/store/selectors/registration.selectors.ts
Labels: ns:xui-mo-webapp-pr-172

#176 removing proxy - attempt to fix the build
  proxy.config.json
Labels: ns:xui-mo-webapp-pr-176

#180 add values for test config
  infrastructure/test_config.tf
Labels: ns:xui-mo-webapp-pr-180

#213 Sending back status to the UI.
  api/register-org/index.ts
Labels: ns:xui-mo-webapp-pr-213

#182 Chore/eui 560 security vulnerabilities aa
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  api/yarn.lock
  package-lock.json
  package.json
  test/e2e/support/reports.js
  yarn.lock
Labels: ns:xui-mo-webapp-pr-182

#214 ITHC config added
  api/lib/config/environments/ithc.config.ts
Labels: ns:xui-mo-webapp-pr-214

#216 changed env pickup on jenkins
  infrastructure/main.tf
Labels: ns:xui-mo-webapp-pr-216

#217 adding ccd roles and jurisdiciton
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/ithc.config.ts
  api/lib/config/environments/local.config.ts
  api/lib/config/environments/preview.config.ts
  src/app/app.constants.ts
Labels: ns:xui-mo-webapp-pr-217

#219 adding probate roles
  src/app/app.constants.ts
Labels: ns:xui-mo-webapp-pr-219

#221 Feature/eui 460 cookie policy
  src/app/app.constants.ts
  src/app/app.routes.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/containers/cookie-policy/cookie-policy.component.html
  src/app/containers/cookie-policy/cookie-policy.component.ts
  src/app/containers/index.ts
Labels: ns:xui-mo-webapp-pr-221

#222 Displaying error message
  src/register/store/reducers/registration.reducer.ts
Labels: ns:xui-mo-webapp-pr-222

#225 EUI-461 privacy policy
  src/app/app.constants.ts
  src/app/app.routes.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts
  src/app/containers/index.ts
  src/app/containers/privacy-policy/privacy-policy.component.html
  src/app/containers/privacy-policy/privacy-policy.component.ts
Labels: ns:xui-mo-webapp-pr-225

#227 Feature/eui 322 t&cs in register journey
  src/register/components/check-your-answers/check-your-answers.component.html
Labels: ns:xui-mo-webapp-pr-227

#228 Feature/eui 613 roles
  src/app/app.constants.ts
  src/users/containers/invite-user/invite-user.component.ts
Labels: ns:xui-mo-webapp-pr-228

#231 None or all roles based on pui-case-manager
  src/app/app.constants.ts
  src/users/containers/invite-user/invite-user.component.ts
Labels: ns:xui-mo-webapp-pr-231

#233 Setup aat env eui 673
  Jenkinsfile_CNP
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/local.config.ts
  test/integration/tests/utils/generateAPI.js
  yarn.lock
Labels: ns:xui-mo-webapp-pr-233

#223 redirect straight to idam after logout
  src/app/store/effects/app.effects.ts
Labels: ns:xui-mo-webapp-pr-223

#240 Clean branch test
  Dockerfile
  README.md
  charts/xui-mo-webapp/requirements.yaml
  charts/xui-mo-webapp/values.template.yaml
Labels: ns:xui-mo-webapp-pr-240

#242 changing footer
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
Labels: ns:xui-mo-webapp-pr-242

#239 changing https_only to true
  infrastructure/main.tf
Labels: ns:xui-mo-webapp-pr-239

#241 Remove hyperlink for the error control
  src/register/components/notification-banner/notification-banner.component.html
Labels: ns:xui-mo-webapp-pr-241

#246 local to prod changes
  api/lib/config/environments/local.config.ts
Labels: ns:xui-mo-webapp-pr-246
