Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2019-10, with the labels that each got.

#271 adding feedback link
  src/shared/components/phase-banner/phase-banner.component.html
Labels: ns:xui-mo-webapp-pr-271

#272 Feature/eui 628 new style user list
  api/userList/index.ts
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.html
  src/users/containers/index.ts
  src/users/containers/user-details/user-details.component.html
  src/users/containers/user-details/user-details.component.scss
  src/users/containers/user-details/user-details.component.ts
  src/users/containers/users/users.component.ts
  src/users/store/effects/users.effects.spec.ts
  src/users/store/effects/users.effects.ts
  src/users/store/reducers/users.reducer.spec.ts
  src/users/store/reducers/users.reducer.ts
  src/users/store/selectors/user.selectors.spec.ts
  src/users/store/selectors/user.selectors.ts
  src/users/users.routing.ts
Labels: Do not merge, ns:xui-mo-webapp-pr-272

#277 Remove deployment block
  Jenkinsfile_CNP
Labels: ns:xui-mo-webapp-pr-277

#273 EUI-902 changed error handling
  api/userList/index.ts
Labels: ns:xui-mo-webapp-pr-273

#278 Feature/eui 140 fee account
  api/accounts/data.mock.ts
  api/accounts/index.ts
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/local.config.ts
  api/payments/index.ts
  api/routes.ts
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.html
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.ts
  src/app/app.constants.ts
  src/app/app.routes.ts
  src/app/models/nav-items.model.ts
  src/app/store/reducers/app.reducer.spec.ts
  src/app/store/reducers/app.reducer.ts
  src/fee-accounts/components/summary/summary.component.html
  src/fee-accounts/containers/account-overview/account-overview.component.spec.ts
  src/fee-accounts/containers/account-overview/account-overview.component.ts
  src/fee-accounts/containers/account-summary/account-summary.component.html
  src/fee-accounts/containers/account-summary/account-summary.component.spec.ts
  src/fee-accounts/containers/account-summary/account-summary.component.ts
  src/fee-accounts/containers/account-transactions/account-transactions.component.html
  src/fee-accounts/containers/account-transactions/account-transactions.component.spec.ts
  src/fee-accounts/containers/account-transactions/account-transactions.component.ts
  src/fee-accounts/containers/overview/account-overview.component.spec.ts
  src/fee-accounts/containers/overview/account-overview.component.ts
  src/fee-accounts/fee-accounts.module.ts
  src/fee-accounts/fee-accounts.routing.ts
  src/fee-accounts/guards/accounts.guard.ts
  src/fee-accounts/models/pba-accounts.ts
  src/fee-accounts/services/fee-accounts.service.ts
  src/fee-accounts/store/actions/fee-accounts.actions.spec.ts
  src/fee-accounts/store/actions/fee-accounts.actions.ts
  src/fee-accounts/store/effects/fee-accounts.effects.spec.ts
  src/fee-accounts/store/effects/fee-accounts.effects.ts
  src/fee-accounts/store/reducers/fee-accounts.reducer.spec.ts
  src/fee-accounts/store/reducers/fee-accounts.reducer.ts
  src/fee-accounts/store/reducers/single-fee-account.reducer.spec.ts
  src/organisation/organisation.model.ts
  src/organisation/store/actions/organisation.actions.spec.ts
  src/users/containers/invite-user-success/invite-user-success.component.ts
  src/users/containers/users/users.component.ts
  src/users/store/reducers/invite-user.reducer.ts
Labels: ns:xui-mo-webapp-pr-278

#279 disable prod deployment for MO
  Jenkinsfile_CNP
Labels: ns:xui-mo-webapp-pr-279

#286 enable tls flag
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/ithc.config.ts
  api/lib/config/environments/local.config.ts
  api/routes.ts
  api/server.ts
Labels: ns:xui-mo-webapp-pr-286

#293 Hiding the Fee and Account Tab
  src/app/app.constants.ts
  src/app/store/reducers/app.reducer.spec.ts
  src/fee-accounts/guards/accounts.guard.ts
Labels: ns:xui-mo-webapp-pr-293
