Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2019-07, with the labels that each got.

#83 chore/repair readme
  README.md
Labels: ns:xui-mo-webapp-pr-83

#86 fixed EUI-225 minor bug
  .gitignore
  api/states/templates/name.ts
  src/users/components/invite-user-form/invite-user-form.component.html
Labels: ns:xui-mo-webapp-pr-86

#87 Feature/eui 44 logout aa
  api/auth/index.ts
  src/app/app.constants.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/containers/header/header.component.html
  src/app/containers/header/header.component.spec.ts
  src/app/containers/header/header.component.ts
  src/app/models/user-nav.model.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effects.spec.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app.reducer.ts
Labels: ns:xui-mo-webapp-pr-87

#88 fixed typo errors in reg org
  .gitignore
  api/states/templates/organisationDx.ts
  api/states/templates/organisationHaveSra.ts
  api/states/templates/organisationName.ts
  api/states/templates/sraNumber.ts
  src/register/components/check-your-answers/check-your-answers.component.html
Labels: ns:xui-mo-webapp-pr-88

#90 EUI-358 bug fix
  api/auth/index.ts
  api/lib/config/index.ts
  api/local.ts
  api/routes.ts
  src/app/app.routes.ts
  src/app/store/effects/app.effects.spec.ts
  src/app/store/effects/app.effects.ts
Labels: ns:xui-mo-webapp-pr-90

#94 bug fix first attempt
  api/auth/index.ts
  api/local.ts
  api/routes.ts
  api/user/index.ts
  api/user/user.ts
  src/app/store/effects/app.effects.spec.ts
  src/app/store/effects/app.effects.ts
  src/user-profile/guards/auth.guard.ts
  src/user-profile/store/actions/user-profile.actions.ts
  src/user-profile/store/effects/user.effects.ts
  src/user-profile/store/reducers/auth.reducer.spec.ts
  src/user-profile/store/reducers/auth.reducer.ts
Labels: ns:xui-mo-webapp-pr-94

#95 removing wrongly committed code
  api/user/index.ts
Labels: ns:xui-mo-webapp-pr-95

#96 EUI-358 redoing cookie removal
  src/app/store/effects/app.effects.ts
Labels: ns:xui-mo-webapp-pr-96

#92 mocha_framework_integration_test_EUI-330
  package-lock.json
  package.json
  test/integration/tests/get_xui_mo_org_details.js
  test/integration/tests/get_xui_mo_org_summary.js
  test/integration/tests/get_xui_mo_orgs.js
  test/integration/tests/test.js
  test/integration/tests/utils/generateAPI.js
  test/integration/tests/utils/getToken.js
  yarn.lock
Labels: ns:xui-mo-webapp-pr-92

#101 title change for Manage Organisations EUI-393
  src/app/app.constants.ts
Labels: ns:xui-mo-webapp-pr-101

#102 Get users by org id
  api/userList/index.ts
  src/users/containers/users/users.component.ts
  src/users/services/users.service.ts
  src/users/store/actions/user.actions.ts
  src/users/store/reducers/index.ts
  src/users/store/reducers/users.reducer.ts
  src/users/store/selectors/user.selectors.spec.ts
  src/users/store/selectors/user.selectors.ts
Labels: ns:xui-mo-webapp-pr-102

#98 Features/fz invite user eui 289
  api/auth/index.ts
  api/lib/stateEngine.ts
  api/routes.ts
  api/user/index.ts
  projects/gov-ui/src/lib/components/hmcts-primary-navigation/hmcts-primary-navigation.component.ts
  src/app/app.constants.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/containers/header/header.component.html
  src/app/containers/header/header.component.ts
  src/app/store/reducers/app.reducer.spec.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/store/selectors/app.selectors.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/organisation/store/actions/organisation.actions.ts
  src/style-guide/components/form/form.component.ts
  src/style-guide/containers/style-guide/style-guide.component.ts
  src/users/components/invite-user-form/invite-user-form.component.html
  src/users/containers/index.ts
  src/users/containers/invite-user/user-form.component.html
  src/users/containers/invite-user/user-form.component.ts
  src/users/users.routing.ts
Labels: ns:xui-mo-webapp-pr-98

#108 Update README.md
  README.md
Labels: ns:xui-mo-webapp-pr-108

#109 Feature/eui 169
  sonar-project.properties
  src/app/services/dummyAppInsights.ts
  src/app/services/monitoring.service.ts
Labels: ns:xui-mo-webapp-pr-109

#110 fixed typo EUI-442
  src/app/app.constants.ts
Labels: ns:xui-mo-webapp-pr-110

#113 Feature/eui 169
  sonar-project.properties
  src/app/services/appInsightsWrapper.ts
  src/app/services/monitoring.service.ts
  src/organisation/organisation.module.ts
  src/shared/shared.module.ts
Labels: ns:xui-mo-webapp-pr-113

#107 changing page titles
  src/app/store/reducers/app.reducer.spec.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
Labels: ns:xui-mo-webapp-pr-107

#112 Feature/eui 284 validations aa
  api/inviteUser/index.ts
  projects/gov-ui/src/lib/gov-ui.module.ts
  projects/gov-ui/src/public_api.ts
  src/app/components/index.ts
  src/fee-accounts/containers/overview/account-overview.component.html
  src/organisation/containers/organisation/organisation.component.html
  src/organisation/organisation.module.ts
  src/shared/components/hmcts-error-summary/hmcts-error-summary.component.ts
  src/shared/components/hmcts-main-wrapper/hmcts-main-wrapper.component.ts
  src/shared/components/success-notification/success-notification.component.html
  src/shared/components/success-notification/success-notification.component.spec.ts
  src/shared/components/success-notification/success-notification.component.ts
  src/shared/services/appInsightsWrapper.ts
  src/shared/services/auth-interceptor.service.ts
  src/shared/services/dummyAppInsights.ts
  src/shared/services/headers.service.spec.ts
  src/shared/services/headers.service.ts
  src/shared/services/http-interceptor.service.ts
  src/shared/services/monitoring.service.spec.ts
  src/shared/services/monitoring.service.ts
  src/shared/shared.module.ts
  src/users/containers/index.ts
  src/users/containers/invite-user-success/invite-user-success.component.html
  src/users/containers/invite-user-success/invite-user-success.component.spec.ts
  src/users/containers/invite-user-success/invite-user-success.component.ts
  src/users/containers/invite-user/invite-user.component.html
  src/users/containers/invite-user/invite-user.component.ts
  src/users/guards/invite-user-success.guard.ts
  src/users/store/actions/invite-user.actions.ts
  src/users/store/actions/user.actions.ts
  src/users/store/effects/index.ts
  src/users/store/effects/invite-user.effects.spec.ts
  src/users/store/effects/invite-user.effects.ts
  src/users/store/effects/users.effects.spec.ts
  src/users/store/effects/users.effects.ts
  src/users/store/reducers/invite-user.reducer.ts
  src/users/store/selectors/invite-user.selector.ts
  src/users/users.module.ts
  src/users/users.routing.ts
Labels: ns:xui-mo-webapp-pr-112

#114 atempt to fix sonar
  sonar-project.properties
Labels: ns:xui-mo-webapp-pr-114

#105 Eui 388 log inand log out automation
  test/e2e/config/conf.js
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/pageObjects/loginLogoutObjects.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/support/constants.js
Labels: ns:xui-mo-webapp-pr-105

#115 Feature/ui validation dx
  api/states/templates/organisationDx.ts
  api/states/templates/organisationPba.ts
  src/register/containers/hmcts-form-builder/src/lib/services/form-builder-custom-validators.service.spec.ts
  src/register/containers/hmcts-form-builder/src/lib/services/form-builder-custom-validators.service.ts
  src/register/containers/hmcts-form-builder/src/lib/services/form-builder-validation.service.ts
  src/register/containers/hmcts-form-builder/src/public_api.ts
Labels: ns:xui-mo-webapp-pr-115

#106 EUI-432-token-functionaltests
  package.json
  test/integration/tests/get_token.js
  test/integration/tests/test.js
  test/integration/tests/utils/generateAPI.js
  test/integration/tests/utils/getToken.js
  yarn.lock
Labels: ns:xui-mo-webapp-pr-106

#111 EUI-258-server-errors
  api/lib/payloadBuilder.spec.ts
  api/lib/payloadBuilder.ts
  api/services/rdProfessional.ts
  api/states/index.ts
  src/organisation/organisation.module.ts
  src/register/components/index.ts
  src/register/components/notification-banner/notification-banner.component.html
  src/register/components/notification-banner/notification-banner.component.spec.ts
  src/register/components/notification-banner/notification-banner.component.ts
  src/register/components/notification-banner/notification-banner.scss
  src/register/containers/register/register.component.html
  src/register/containers/register/register.component.ts
  src/register/mappings/apiErrorMappings.ts
  src/register/store/actions/registration.action.spec.ts
  src/register/store/actions/registration.actions.ts
  src/register/store/reducers/registration.reducer.spec.ts
  src/register/store/reducers/registration.reducer.ts
  src/register/store/selectors/registration.selectors.spec.ts
  src/register/store/selectors/registration.selectors.ts
  src/shared/services/monitoring.service.spec.ts
  src/shared/shared.module.ts
Labels: ns:xui-mo-webapp-pr-111

#117 Fix formating issue
  src/organisation/containers/organisation/organisation.component.html
Labels: ns:xui-mo-webapp-pr-117

#119 EUI-368 build prod in production
  package.json
  src/app/app.module.ts
  src/shared/components/hmcts-main-wrapper/hmcts-main-wrapper.component.ts
  src/style-guide/containers/style-guide/style-guide.component.html
Labels: ns:xui-mo-webapp-pr-119

#120 Updating app module
  src/app/app.module.ts
Labels: ns:xui-mo-webapp-pr-120

#122 Feature/eui 458 fix back button
  src/register/containers/register/register.component.ts
  src/register/store/actions/registration.actions.ts
  src/register/store/reducers/registration.reducer.ts
Labels: ns:xui-mo-webapp-pr-122

#124 Feature/eui 451 end point integration
  api/auth/index.ts
  api/auth/serviceToken.ts
  api/inviteUser/index.ts
  api/lib/config/application.config.ts
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/local.config.ts
  api/lib/config/environments/preview.config.ts
  api/lib/serviceToken.ts
  api/organisation/index.ts
  api/routes.ts
  api/server.ts
  api/services/rdProfessional.ts
  api/services/serviceAuth.ts
  api/tslint.json
  api/userList/index.ts
  charts/xui-mo-webapp/values.aat.template.yaml
  infrastructure/main.tf
  src/organisation/services/organisation.service.ts
  src/shared/services/headers.service.ts
  src/user-profile/services/user.service.ts
  yarn.lock
Labels: ns:xui-mo-webapp-pr-124

#123 Feature/eui 452 shuttering aa
  api/healthCheck/index.ts
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/docker.config.ts
  api/lib/config/environments/ldocker.config.ts
  api/lib/config/environments/local.config.ts
  api/lib/config/environments/mock.config.ts
  api/lib/config/environments/preview.config.ts
  api/lib/config/environments/prod.config.ts
  api/lib/config/environments/saat.config.ts
  api/lib/config/environments/spreview.config.ts
  api/lib/config/environments/sprod.config.ts
  api/routes.ts
  src/app/app.routes.ts
  src/app/containers/index.ts
  src/app/containers/service-down/service-down.component.html
  src/app/containers/service-down/service-down.component.ts
  src/app/store/reducers/index.ts
  src/organisation/organisation.routing.ts
  src/register/register.routing.ts
  src/shared/guards/health-check.guard.spec.ts
  src/shared/guards/health-check.guard.ts
  src/shared/services/health-check.service.spec.ts
  src/shared/services/health-check.service.ts
  src/shared/shared.module.ts
  src/user-profile/guards/auth.guard.spec.ts
  src/users/users.routing.ts
  tslint.json
Labels: ns:xui-mo-webapp-pr-123

#125 Making the MO work with Logger/Monitoring Service
  package-lock.json
  package.json
  src/organisation/organisation.module.ts
  src/shared/services/logger.service.spec.ts
  src/shared/services/logger.service.ts
  yarn.lock
Labels: ns:xui-mo-webapp-pr-125

#129 Feature/fz redirect url eui 513
  src/app/containers/app/app.component.ts
  src/app/store/reducers/app.reducer.ts
  src/styles.scss
  src/user-profile/guards/auth.guard.ts
Labels: ns:xui-mo-webapp-pr-129

#130 removing permission redirect to pass sonar
  src/app/containers/app/app.component.ts
Labels: ns:xui-mo-webapp-pr-130

#126 EUI-466 users tab
  src/app/app.constants.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/users/containers/users/users.component.ts
  src/users/store/reducers/users.reducer.ts
Labels: ns:xui-mo-webapp-pr-126

#136 Fix for the error
  projects/hmcts-form-builder/src/lib/components/validation-header/validation-header.component.html
  projects/hmcts-form-builder/src/lib/components/validation-header/validation-header.component.ts
  src/register/containers/hmcts-form-builder/src/lib/components/validation-header/validation-header.component.html
  src/register/containers/hmcts-form-builder/src/lib/components/validation-header/validation-header.component.ts
Labels: ns:xui-mo-webapp-pr-136

#128 EUI-408 Phase banner addition
  src/app/containers/header/header.component.html
  src/shared/components/phase-banner/phase-banner.component.html
  src/shared/components/phase-banner/phase-banner.component.ts
  src/shared/shared.module.ts
Labels: ns:xui-mo-webapp-pr-128

#135 changing microservice id
  api/lib/config/application.config.ts
  api/services/serviceAuth.ts
Labels: ns:xui-mo-webapp-pr-135
