Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2019-06, with the labels that each got.

#60 Chore/new test branch test
  api/package.json
  api/routes.ts
  api/server.ts
  charts/xui-manage-organisations/Chart.yaml
  package.json
Labels: ns:xui-manage-organisations-pr-60

#64 chore/add pr white list fix
  whitelist.sh
Labels: ns:xui-manage-organisations-pr-64

#62 Feature/fz header eui 49
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/containers/header/header.component.html
  src/app/containers/header/header.component.ts
  src/app/models/app-titles.model.ts
  src/app/models/nav-items.model.ts
  src/app/models/user-nav.model.ts
  src/app/store/effects/app.effects.spec.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/store/selectors/app.selectors.ts
  src/fee-accounts/fee-accounts.routing.ts
  src/karma.conf.js
Labels: ns:xui-manage-organisations-pr-62

#63 EUI-69 Add automation framework and test
  .gitignore
  package.json
  test/e2e/config/conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/config/protractor.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/createOrganisation.feature
  test/e2e/features/pageObjects/createOrganisationObjects.js
  test/e2e/features/pageObjects/dummyObjects.steps.js
  test/e2e/features/step_definitions/steps/createOrganisation.steps.js
  test/e2e/features/step_definitions/steps/dummy.steps.js
  test/e2e/support/config.js
  test/e2e/support/constants.js
  test/e2e/support/hooks.js
  test/e2e/support/reports.js
  test/e2e/support/tagProcessor.js
  test/e2e/support/timeout.js
  test/e2e/support/world.js
  yarn.lock
Labels: ns:xui-manage-organisations-pr-63

#67 bug/correct logger
  api/server.ts
  api/userList/index.ts
Labels: ns:xui-manage-organisations-pr-67

#68 Add automation framework
  test/e2e/config/conf.js
Labels: ns:xui-manage-organisations-pr-68

#69 Updating microservice
  api/lib/config/application.config.ts
Labels: ns:xui-mo-webapp-pr-69

#70 chore/remove bad charcter from call back
  src/auth/services/auth.service.ts
  whitelist.sh
Labels: ns:xui-mo-webapp-pr-70

#71 Register Organisation with backend as part of Manage App
  api/interfaces/organisationPayload.ts
  api/lib/config/application.config.ts
  api/lib/config/environments/ldocker.config.ts
  api/lib/payloadBuilder.ts
  api/local.ts
  api/services/serviceAuth.ts
  package.json
Labels: ns:xui-mo-webapp-pr-71

#75 Rd docker integration
  api/accounts/index.spec.ts
  api/interfaces/organisationPayload.ts
  api/lib/config/application.config.ts
  api/lib/config/environments/ldocker.config.ts
  api/lib/payloadBuilder.spec.ts
  api/lib/payloadBuilder.ts
  api/local.ts
  api/package.json
  api/services/serviceAuth.ts
  package.json
Labels: ns:xui-mo-webapp-pr-75

#80 remove api/node_modules
  .gitignore
  api/lib/tunnel.ts
  api/local.ts
  api/node_modules/.cache/nyc/02e52b8186373a27ba9273ed64cf178d5754b183b36e3f163e0a86a4cbe52968.map
  api/node_modules/.cache/nyc/02e52b8186373a27ba9273ed64cf178d5754b183b36e3f163e0a86a4cbe52968.ts
  api/node_modules/.cache/nyc/120dff2f0526f765a32d1691abf516645597a65ec1ca13036a9d1eceb4224ae4.map
  api/node_modules/.cache/nyc/120dff2f0526f765a32d1691abf516645597a65ec1ca13036a9d1eceb4224ae4.ts
  api/node_modules/.cache/nyc/254e304941b486143ddc82360883d616692a8a7c48963b47fe277407e5dc98ac.map
  api/node_modules/.cache/nyc/254e304941b486143ddc82360883d616692a8a7c48963b47fe277407e5dc98ac.ts
  api/node_modules/.cache/nyc/27791ca3a52e2e556f8a73bdf036ae758346983f0916109b247723839b53d62e.map
  api/node_modules/.cache/nyc/27791ca3a52e2e556f8a73bdf036ae758346983f0916109b247723839b53d62e.ts
  api/node_modules/.cache/nyc/2c3cf3e98a409953e9f5eb5f93427eba87780daebc9f95d9002d3435714636c7.map
  api/node_modules/.cache/nyc/2c3cf3e98a409953e9f5eb5f93427eba87780daebc9f95d9002d3435714636c7.ts
  api/node_modules/.cache/nyc/3a8ec7a6280641bd894b3fa1d58f192b895c722429da0a351b389f3d71ac629b.map
  api/node_modules/.cache/nyc/3a8ec7a6280641bd894b3fa1d58f192b895c722429da0a351b389f3d71ac629b.ts
  api/node_modules/.cache/nyc/3b2cccaf75260ea51f96c932eff2e2a1d3f6db936ecebf56965e5266c4e373ea.map
  api/node_modules/.cache/nyc/3b2cccaf75260ea51f96c932eff2e2a1d3f6db936ecebf56965e5266c4e373ea.ts
  api/node_modules/.cache/nyc/4ee0fee77e1ed94c72d474ac21d09d0fcd19d423660dcc3aba04edf293fad89c.map
  api/node_modules/.cache/nyc/4ee0fee77e1ed94c72d474ac21d09d0fcd19d423660dcc3aba04edf293fad89c.ts
  api/node_modules/.cache/nyc/5a7cbd7f28f7e53d84f71c21e4a79212a9d93f4b8bcf1d5273dba1d660ed5645.map
  api/node_modules/.cache/nyc/5a7cbd7f28f7e53d84f71c21e4a79212a9d93f4b8bcf1d5273dba1d660ed5645.ts
  api/node_modules/.cache/nyc/780e1f35b6281ad9a1de6249b36a8c4aaba11ac8217225fdbff220aab8e0acf0.map
  api/node_modules/.cache/nyc/780e1f35b6281ad9a1de6249b36a8c4aaba11ac8217225fdbff220aab8e0acf0.ts
  api/node_modules/.cache/nyc/8a0162b1898297e74f5d007a761f9e70501347da742b4256abe8b6489c06b079.map
  api/node_modules/.cache/nyc/8a0162b1898297e74f5d007a761f9e70501347da742b4256abe8b6489c06b079.ts
  api/node_modules/.cache/nyc/8fbddf1bfcde64aa1724aacb896d7640a81cf2f04eccf25f54ae3856cd802ff9.map
  api/node_modules/.cache/nyc/8fbddf1bfcde64aa1724aacb896d7640a81cf2f04eccf25f54ae3856cd802ff9.ts
  api/node_modules/.cache/nyc/95013c2ca38677141ca47286c0f33f3a07548ec2298c147e787f87c89f5291b2.map
  api/node_modules/.cache/nyc/95013c2ca38677141ca47286c0f33f3a07548ec2298c147e787f87c89f5291b2.ts
  api/node_modules/.cache/nyc/97b5d5fe43beb116809b33332d9c0209d2539e0b67193334e92deed46617b5e4.map
  api/node_modules/.cache/nyc/97b5d5fe43beb116809b33332d9c0209d2539e0b67193334e92deed46617b5e4.ts
  api/node_modules/.cache/nyc/a0a2ddb5dc2f15a1b51968bc136ebc43c050cf6738d98344f5b2af07ff6aa25b.map
  api/node_modules/.cache/nyc/a0a2ddb5dc2f15a1b51968bc136ebc43c050cf6738d98344f5b2af07ff6aa25b.ts
  api/node_modules/.cache/nyc/a35e8c273fd23041ccba081b83fa2f453138e4d94f1cd5351ac8ff42c4a139c7.map
  api/node_modules/.cache/nyc/a35e8c273fd23041ccba081b83fa2f453138e4d94f1cd5351ac8ff42c4a139c7.ts
  api/node_modules/.cache/nyc/aa3e1ac672b3fe483b5cf713f6b8737d498f376c9e0156feda41224094e6fd63.map
  api/node_modules/.cache/nyc/aa3e1ac672b3fe483b5cf713f6b8737d498f376c9e0156feda41224094e6fd63.ts
  api/node_modules/.cache/nyc/b56a4aefc021397636959fc3f8b19a6b700e1f17732f80727838171cb8db9b48.map
  api/node_modules/.cache/nyc/b56a4aefc021397636959fc3f8b19a6b700e1f17732f80727838171cb8db9b48.ts
  api/node_modules/.cache/nyc/c85562dec880406bc52a058f38a03c959c4217e3a155f0fec4c9f2ad43219902.map
  api/node_modules/.cache/nyc/c85562dec880406bc52a058f38a03c959c4217e3a155f0fec4c9f2ad43219902.ts
  api/node_modules/.cache/nyc/cd07fec98ee5c808d3486d504dd660cc071938b4c44dc0e14bd0dfbdc01b5c6e.map
  api/node_modules/.cache/nyc/cd07fec98ee5c808d3486d504dd660cc071938b4c44dc0e14bd0dfbdc01b5c6e.ts
  api/node_modules/.cache/nyc/ceaaa4a17e4dafd7101e50180608107718afce42dfce51233185a9c94dc73780.map
  api/node_modules/.cache/nyc/ceaaa4a17e4dafd7101e50180608107718afce42dfce51233185a9c94dc73780.ts
  api/node_modules/.cache/nyc/dd888cb1fab3c803eed55a5ddf26c89597642fb65427d4932677995fcac2e947.map
  api/node_modules/.cache/nyc/dd888cb1fab3c803eed55a5ddf26c89597642fb65427d4932677995fcac2e947.ts
  api/node_modules/.cache/nyc/ebe9907d6ebe5946cf5d94c1f2cdd682e15e3f258cf4dd98b3cf9b2ef3929cff.map
  api/node_modules/.cache/nyc/ebe9907d6ebe5946cf5d94c1f2cdd682e15e3f258cf4dd98b3cf9b2ef3929cff.ts
  api/node_modules/.cache/nyc/f39110d378781fc147eac3c5a10d8349d9dfae9eb59075bd6c632354dc08b7b0.map
  api/node_modules/.cache/nyc/f39110d378781fc147eac3c5a10d8349d9dfae9eb59075bd6c632354dc08b7b0.ts
  api/services/serviceAuth.ts
Labels: ns:xui-mo-webapp-pr-80

#74 EUI-225 amended checkboxes
  src/users/components/invite-user-form/invite-user-form.component.html
Labels: ns:xui-mo-webapp-pr-74

#73 EUI-254 Table width reduced and mfa column removed
  src/users/containers/users/users.component.html
  src/users/containers/users/users.component.scss
  src/users/containers/users/users.component.ts
Labels: ns:xui-mo-webapp-pr-73

#82 master test -28-6-19
  README.md
  src/auth/services/auth.service.ts
Labels: ns:xui-mo-webapp-pr-82
