Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2019-09, with the labels that each got.

#252 reorder parameters
  src/user-profile/guards/auth.guard.ts
Labels: ns:xui-mo-webapp-pr-252

#254 Bug/fz configuration fix 2
  api/lib/config/environments/preview.config.ts
  src/app/app.constants.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/user-profile/guards/auth.guard.ts
Labels: ns:xui-mo-webapp-pr-254

#266 change s2s protocol to http
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/ithc.config.ts
  api/lib/config/environments/mock.config.ts
  api/lib/config/environments/prod.config.ts
  api/lib/config/environments/saat.config.ts
  api/lib/config/environments/spreview.config.ts
  api/lib/config/environments/sprod.config.ts
Labels: ns:xui-mo-webapp-pr-266

#268 Feature/eui 537 accessibility aa master
  src/app/app.constants.ts
  src/app/app.routes.ts
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.ts
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/cookie-policy/cookie-policy.component.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/index.ts
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/privacy-policy/privacy-policy.component.ts
  src/app/components/service-down/service-down.component.html
  src/app/components/service-down/service-down.component.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/components/terms-and-conditions/terms-and-conditions.component.ts
  src/app/containers/index.ts
  src/app/containers/privacy-policy/privacy-policy.component.ts
Labels: ns:xui-mo-webapp-pr-268

#269 adding unit test
  src/app/components/accessibility/accessibility.component.spec.ts
  src/app/components/cookie-policy/cookie-policy.component.spec.ts
  src/app/components/privacy-policy/privacy-policy.component.spec.ts
Labels: ns:xui-mo-webapp-pr-269

#267 Feature/eui 589 pba validator minlength
  src/register/constants/pbaNumber.ts
  src/register/containers/hmcts-form-builder/src/lib/services/form-builder-validation.service.ts
  src/register/containers/hmcts-form-builder/src/lib/services/form-builder.service.ts
Labels: ns:xui-mo-webapp-pr-267

#265 DO NOT MERGE - CAB candidate: Feature/EUI 727 dx example and validation
  src/register/constants/organisationDx.ts
  src/register/containers/hmcts-form-builder/src/lib/services/form-builder-validation.service.ts
Labels: ns:xui-mo-webapp-pr-265

#262 EUI-657 making the registration success page to 2/3 width
  src/register/components/submitted-confirmation/submitted-confirmation.component.ts
Labels: ns:xui-mo-webapp-pr-262

#259 EUI_761_postcode_Fixed
  api/lib/payloadBuilder.ts
  src/app/utils/app-utils.ts
  src/organisation/containers/organisation/organisation.component.html
  src/register/components/check-your-answers/check-your-answers.component.html
  src/register/models/form-data-values.model.ts
Labels: ns:xui-mo-webapp-pr-259

#260 DO NOT MERGE: Minify the NG code produced
  Jenkinsfile_CNP
  api/lib/config/environments/local.config.ts
  package.json
Labels: ns:xui-mo-webapp-pr-260

#263 Eui 729 accessibility from master
  package.json
  projects/gov-ui/src/lib/components/gov-uk-checkbox/gov-uk-checkbox.component.ts
  projects/gov-ui/src/lib/components/gov-uk-fieldset/gov-uk-fieldset.component.ts
  projects/hmcts-form-builder/src/lib/assets/sass/application.scss
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/assets/components/button/_button.scss
  src/assets/components/case-actions/_case-actions.scss
  src/assets/components/casefile/_casefile-2.scss
  src/assets/components/casefile/_casefile-3.scss
  src/assets/components/casefile/_casefile.scss
  src/assets/components/tabs/_tabs.scss
  src/assets/components/tree/_tree.scss
  src/assets/sass/application.scss
  src/assets/sass/patterns/_pba.scss
  src/register/containers/hmcts-form-builder/src/lib/assets/sass/application.scss
  src/register/containers/register/register.component.html
  yarn.lock
Labels: ns:xui-mo-webapp-pr-263
