Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2019-11, with the labels that each got.

#302 Pact integration
  .gitignore
  Jenkinsfile_CNP
  api/auth/index.ts
  api/services/idam.ts
  api/test/pact/pact-tests/test.spec.ts
  api/test/pact/publish/publish.js
  package.json
  yarn.lock
Labels: ns:xui-mo-webapp-pr-302

#297 update the branded MyHMCTS
  projects/gov-ui/src/lib/components/hmcts-primary-navigation/hmcts-primary-navigation.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
Labels: ns:xui-mo-webapp-pr-297

#300 Adding new SRA message mapping..
  src/register/mappings/apiErrorMappings.ts
Labels: ns:xui-mo-webapp-pr-300

#291 updating to the latest prototype accessibility
  src/app/components/accessibility/accessibility.component.html
Labels: ns:xui-mo-webapp-pr-291

#236 Bug/eui 677 DO NOT MERGE
  src/users/containers/invite-user-success/invite-user-success.component.html
  src/users/containers/invite-user-success/invite-user-success.component.ts
  src/users/models/userform.model.ts
  src/users/store/effects/invite-user.effects.spec.ts
  src/users/store/effects/invite-user.effects.ts
  src/users/store/reducers/invite-user.reducer.ts
  src/users/store/selectors/invite-user.selector.ts
Labels: ns:xui-mo-webapp-pr-236

#310 fixing the missing name on pending
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.html
Labels: ns:xui-mo-webapp-pr-310

#311 Update FPLA ccd roles in MO
  src/app/app.constants.ts
Labels: CABApproved, ns:xui-mo-webapp-pr-311

#304 Update to error mappings.
  src/register/mappings/apiErrorMappings.ts
Labels: CABApproved, ns:xui-mo-webapp-pr-304

#287 EUI-668 updating the error messages for invite user
  src/users/containers/invite-user/invite-user.component.ts
Labels: CABApproved, ns:xui-mo-webapp-pr-287

#305 update both date to be 16 september
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.ts
Labels: CABApproved, ns:xui-mo-webapp-pr-305

#307 adding google analytics
  package.json
  src/app/app.module.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  yarn.lock
Labels: CABApproved, ns:xui-mo-webapp-pr-307

#306 adding branded header toggle
  projects/gov-ui/src/lib/components/hmcts-primary-navigation/hmcts-primary-navigation.component.html
  projects/gov-ui/src/lib/components/hmcts-primary-navigation/hmcts-primary-navigation.component.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/containers/header/header.component.html
  src/app/containers/header/header.component.ts
Labels: CABApproved, ns:xui-mo-webapp-pr-306

#308 Add api version for helm chart
  charts/xui-mo-webapp/Chart.yaml
Labels: ns:xui-mo-webapp-pr-308

#290 AWAITING CAB: Restrict access to only Manage Organisation Users.
  api/auth/index.ts
  api/auth/userRoleAuth.spec.ts
  api/auth/userRoleAuth.ts
  api/lib/objectUtilities.spec.ts
  api/lib/objectUtilities.ts
Labels: CABApproved, ns:xui-mo-webapp-pr-290

#145 Mo automations
  test/e2e/config/conf.js
  test/e2e/features/app/createOrganisation.feature
  test/e2e/features/app/inviteUser.feature
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/viewOrganisation.feature
  test/e2e/features/app/viewUser.feature
  test/e2e/features/pageObjects/createOrganisationObjects.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/inviteUserPage.js
  test/e2e/features/pageObjects/loginLogoutObjects.js
  test/e2e/features/pageObjects/viewOrganisationPage.js
  test/e2e/features/pageObjects/viewUserPage.js
  test/e2e/features/pageObjects/webdriver-components/button.js
  test/e2e/features/pageObjects/webdriver-components/dropdown.js
  test/e2e/features/pageObjects/webdriver-components/radioField.js
  test/e2e/features/pageObjects/webdriver-components/textField.js
  test/e2e/features/step_definitions/createOrganisation.steps.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/viewOrganisation.steps.js
  test/e2e/features/step_definitions/viewUser.steps.js
  test/e2e/utils/TestData.js
  test/e2e/utils/errors/custom-error.js
  test/e2e/utils/euiDataGenerationUtils.js
Labels: Automation, ns:xui-mo-webapp-pr-145

#312 adding new copy to registration T&C
  src/register/components/check-your-answers/check-your-answers.component.html
Labels: ns:xui-mo-webapp-pr-312

#301 cleaned up env variable and fixed base docker image
  Dockerfile
  api/auth/index.ts
  api/lib/tunnel.ts
  api/local.ts
  api/routes.ts
  api/server.ts
  charts/xui-mo-webapp/values.aat.template.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
  whitelist.sh
Labels: ns:xui-mo-webapp-pr-301

#274 DONT MERGE: Integration tests with new token
  Jenkinsfile_CNP
  api/lib/config/environments/local.config.ts
  package-lock.json
  package.json
  test/integration/tests/get_Organisation_Details.ts
  test/integration/tests/get_Organisation_User_Details.ts
  test/integration/tests/get_token.js
  test/integration/tests/post_Invite_User.ts
  test/integration/tests/test.js
  test/integration/tests/test.ts
  test/integration/tests/utils/generateAPI.js
  test/integration/tests/utils/generateAPI.ts
  test/integration/tests/utils/generatePOSTAPI.ts
  test/integration/tests/utils/getToken.js
  test/integration/tests/utils/getToken.ts
  test/integration/tests/utils/index.ts
  yarn.lock
Labels: Automation
