Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2020-07, with the labels that each got.

#524 Hotfix terraform
  .github/stale.yml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-524

#525 handle roleDeletionResponse
  package.json
  src/app/containers/app/app.component.spec.ts
  src/users/containers/user-details/user-details.component.html
  src/users/containers/user-details/user-details.component.ts
  src/users/containers/utils/user-roles-util.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-525

#523 Feature/unassigned cases
  src/app/app-initializer.ts
  src/app/app.constants.ts
  src/app/app.routes.ts
  src/app/containers/app/app.component.ts
  src/app/store/selectors/app.selectors.ts
  src/unassigned-cases/containers/index.ts
  src/unassigned-cases/containers/unassinged-cases/unassigned-cases.component.html
  src/unassigned-cases/containers/unassinged-cases/unassigned-cases.component.ts
  src/unassigned-cases/guards/feature-toggle.guard.ts
  src/unassigned-cases/guards/user-role.guard.ts
  src/unassigned-cases/unassigned-cases.module.ts
  src/unassigned-cases/unassigned-cases.routing.ts
  src/user-profile/store/selectors/auth.selectors.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-523

#531 Fix pending user re invite
  src/users/containers/user-details/user-details.component.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-531

#535 update dependencies
  package-lock.json
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-535

#542 MO Add app insight
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-542

#543 update dependencies for CVE & Add App Insights
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
  package-lock.json
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-543
