Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2020-03, with the labels that each got.

#432 Feature/master into develop 2
  Jenkinsfile_CNP
  api/.env.defaults
  api/auth/index.ts
  api/configuration/health.ts
  api/configuration/index.ts
  api/configuration/references.ts
  api/configuration/ui.ts
  api/getUserTermsAndConditions/index.ts
  api/healthCheck/index.ts
  api/interfaces/environment.config.ts
  api/lib/appInsights.ts
  api/lib/s2sTokenGeneration.ts
  api/lib/tunnel.ts
  api/local.ts
  api/routes.ts
  api/server.ts
  api/services/serviceAuth.ts
  charts/xui-mo-webapp/values.aat.template.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  package.json
  src/accept-tc/guards/acceptTermsAndCondition.guard.spec.ts
  src/accept-tc/guards/acceptTermsAndCondition.guard.ts
  src/app/app.constants.ts
  src/app/app.routes.ts
  src/app/components/index.ts
  src/app/components/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html
  src/app/components/legacy-terms-and-conditions/legacy-terms-and-conditions.component.ts
  src/app/guards/termsCondition.guard.ts
  src/app/store/reducers/app.reducer.spec.ts
  src/fee-accounts/guards/accounts.guard.ts
  src/users/containers/user-details/user-details.component.html
  src/users/containers/user-details/user-details.component.ts
  test/e2e/features/step_definitions/createOrganisation.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
Labels: ns:xui, rel:xui-mo-webapp-pr-432

#436 Terms And Conditions as feature
  api/configValueRouter/index.ts
  api/configuration/health.ts
  api/configuration/index.ts
  api/healthCheck/healthCheckUtil.ts
  api/healthCheck/index.ts
  api/interfaces/environment.config.ts
  api/routes.ts
  src/app/guards/termsCondition.guard.spec.ts
  src/app/guards/termsCondition.guard.ts
  src/shared/services/termsConditions.service.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-436

#439 Moving feature toggle to open route so that it will be used in regist…
  api/openRoutes.ts
  api/routes.ts
  src/register/components/check-your-answers/check-your-answers.component.html
  src/register/components/check-your-answers/check-your-answers.component.ts
  src/shared/services/termsConditions.service.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-439

#441 UI retrieves Idam Web configuration setting from the node layer.
  api/configurationUI/index.ts
  api/openRoutes.ts
  src/app/store/effects/app.effects.ts
  src/models/environmentConfig.model.ts
  src/shared/services/environment.service.spec.ts
  src/shared/services/environment.service.ts
  src/user-profile/guards/auth.guard.spec.ts
  src/user-profile/guards/auth.guard.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-441

#445 Feature/helmet on master 3
  api/configuration/references.ts
  api/local.ts
  api/server.ts
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package-lock.json
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-445

#447 Feature/merge master into develop
  Jenkinsfile_CNP
  api/configValueRouter/index.ts
  api/configuration/health.ts
  api/configuration/index.ts
  api/configuration/references.ts
  api/configurationUI/index.ts
  api/healthCheck/healthCheckUtil.ts
  api/healthCheck/index.ts
  api/interfaces/environment.config.ts
  api/local.ts
  api/openRoutes.ts
  api/server.ts
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/requirements.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package-lock.json
  package.json
  src/app/guards/termsCondition.guard.spec.ts
  src/app/guards/termsCondition.guard.ts
  src/app/store/effects/app.effects.ts
  src/models/environmentConfig.model.ts
  src/register/components/check-your-answers/check-your-answers.component.html
  src/register/components/check-your-answers/check-your-answers.component.ts
  src/shared/services/environment.service.spec.ts
  src/shared/services/environment.service.ts
  src/shared/services/termsConditions.service.ts
  src/user-profile/guards/auth.guard.spec.ts
  src/user-profile/guards/auth.guard.ts
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-447

#446 Set cloudRole name in app insights
  api/lib/appInsights.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-446

#431 Feature/eui 1520 use common lib user component
  package.json
  src/users/containers/user-details/user-details.component.html
  src/users/containers/user-details/user-details.component.spec.ts
  src/users/containers/user-details/user-details.component.ts
  src/users/containers/users/users.component.html
  src/users/containers/users/users.component.ts
  src/users/store/reducers/users.reducer.spec.ts
  src/users/store/reducers/users.reducer.ts
  src/users/users.module.ts
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-431

#452 change the suspend user contact content
  package.json
  src/users/containers/user-details/user-details.component.html
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-452

#454 Feature/redis session cache v2
  .gitignore
  api/.env.defaults
  api/.env.example
  api/application.ts
  api/auth/index.ts
  api/configuration/index.ts
  api/configuration/references.ts
  api/configuration/ui.ts
  api/lib/log4jui.ts
  api/lib/models/index.ts
  api/lib/sessionStore.ts
  api/lib/tunnel.ts
  api/local.ts
  api/server.ts
  api/services/serviceAuth.ts
  api/tsconfig.json
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/requirements.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-454

#460 bumped chart version and enabled terms and conditions
  api/configurationUI/index.ts
  api/lib/appInsights.ts
  api/services/serviceAuth.ts
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  src/models/environmentConfig.model.ts
  src/shared/services/environment.service.ts
  src/user-profile/guards/auth.guard.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-460

#466 added node healthcheck library and endpoints
  api/application.ts
  api/lib/sessionStore.ts
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-466

#468 fixed issue where GA key was not being pulled in correctly
  src/app/containers/app/app.component.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-468
