Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2020-05, with the labels that each got.

#498 clean ase
  Jenkinsfile_CNP
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/requirements.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:xui, rel:xui-mo-webapp-pr-498

#473 Feature/launch darkly
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  api/auth/index.ts
  api/configuration/references.ts
  api/configurationUI/index.ts
  api/customTypings/customExpress/index.d.ts
  api/lib/interceptors.ts
  api/organisation/index.ts
  api/package.json
  api/tsconfig.json
  charts/xui-mo-webapp/values.aat.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  package.json
  src/app/app-initializer.ts
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/models/nav-items.model.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effects.spec.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app.reducer.spec.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/fee-accounts/fee-accounts.module.ts
  src/fee-accounts/fee-accounts.routing.ts
  src/fee-accounts/guards/accounts.guard.ts
  src/fee-accounts/guards/feature-toggle-account.guard.ts
  src/main.ts
  src/models/environmentConfig.model.ts
  src/register/containers/register/register.component.ts
  src/shared/services/environment.service.spec.ts
  src/shared/services/headers.service.ts
  src/shared/shared.module.ts
  src/user-profile/guards/auth.guard.ts
  src/users/containers/edit-user-permissions/edit-user-permission.component.ts
  src/users/containers/user-details/user-details.component.html
  src/users/containers/user-details/user-details.component.spec.ts
  src/users/containers/user-details/user-details.component.ts
  src/users/guards/feature-toggle-edit-user.guard.ts
  src/users/users.routing.ts
  src/web.config
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-473

#499 Chnaged Referenece to rpx-common-lib to 0.1.11
  package.json
  src/users/containers/user-details/user-details.component.html
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-499

#501 remove app setting
  Jenkinsfile_CNP
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:xui, rel:xui-mo-webapp-pr-501

#471 Registration details submit content update
  src/register/components/submitted-confirmation/submitted-confirmation.component.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-471

#457 Tests/eui 1647 mutation tests
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  api/test/mocha.opts
  config/default.json
  package.json
  src/app/utils/app-utils.ts
  stryker.node.conf.js
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-457

#500 Feature/eui 1690 fix
  api/editUserPermissions/index.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/user-profile/store/effects/user-profile.effects.ts
  src/users/containers/utils/user-roles-util.spec.ts
  src/users/containers/utils/user-roles-util.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-500

#496 Content update for invite user success
  src/users/containers/invite-user-success/invite-user-success.component.html
Labels: ns:xui, rel:xui-mo-webapp-pr-496

#494 Added contact info for get help page
  src/app/components/get-help/get-help.component.html
Labels: ns:xui, rel:xui-mo-webapp-pr-494

#470 EUI-1699 increased timeout duration
  api/application.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-470

#506 Enable myHMCTS header
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/containers/header/header.component.ts
  src/styles.scss
  test/e2e/features/pageObjects/loginLogoutObjects.js
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-506

#502 updated vesrions for several packages for sonar reports
  angular.json
  api/auth/index.ts
  package.json
  sonar-project.properties
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-502

#391 Hotfix/ZAP Setting EUI-1472
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  security.sh
Labels: ns:xui, rel:xui-mo-webapp-pr-391

#507 Tests/eui 1974 ui smoketests
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  test/e2e/config/fullfunctional.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/smoke.feature
  test/e2e/features/step_definitions/createOrganisation.steps.js
Labels: ns:xui, rel:xui-mo-webapp-pr-507

#511 pa11y tests implementation
  Jenkinsfile_CNP
  package-lock.json
  package.json
  test/accessibility/config/config.js
  test/accessibility/helpers/applicationActions.js
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/helpers/pallyActions.js
  test/accessibility/reporter/Report.html
  test/accessibility/reporter/customReporter.js
  test/accessibility/reporter/resources/angular.min.js
  test/accessibility/reporter/resources/css/all.css
  test/accessibility/reporter/resources/webfonts/fa-solid-900.woff2
  test/accessibility/tests/index.js
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-511

#512 Enable a11y in nightly pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
Labels: ns:xui, rel:xui-mo-webapp-pr-512
