Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2020-01, with the labels that each got.

#341 Update tslint.json to new rules
  package-lock.json
  package.json
  src/users/containers/user-details/user-details.component.ts
  tslint.json
  yarn.lock
Labels: ns:xui-mo-webapp-pr-341

#343 EUI-1314 test coverage for effect errors
  src/app/store/effects/app.effects.spec.ts
  src/app/store/effects/app.effects.ts
  src/fee-accounts/store/effects/single-fee-account.effects.spec.ts
  src/fee-accounts/store/effects/single-fee-account.effects.ts
  src/organisation/store/effects/organisation.effects.spec.ts
  src/organisation/store/effects/organisation.effects.ts
  src/register/store/effects/registration.effects.spec.ts
  src/register/store/effects/registration.effects.ts
  src/user-profile/store/effects/user.effects.spec.ts
  src/user-profile/store/effects/user.effects.ts
Labels: ns:xui-mo-webapp-pr-343

#344 Chore/eui 1315 add logger service aa
  src/app/store/effects/app.effects.spec.ts
  src/app/store/effects/app.effects.ts
  src/fee-accounts/store/effects/fee-accounts.effects.spec.ts
  src/fee-accounts/store/effects/fee-accounts.effects.ts
  src/fee-accounts/store/effects/single-fee-account.effects.spec.ts
  src/fee-accounts/store/effects/single-fee-account.effects.ts
  src/organisation/store/effects/organisation.effects.spec.ts
  src/organisation/store/effects/organisation.effects.ts
  src/register/store/effects/registration.effects.spec.ts
  src/register/store/effects/registration.effects.ts
  src/user-profile/store/effects/user.effects.spec.ts
  src/user-profile/store/effects/user.effects.ts
  src/users/store/effects/users.effects.spec.ts
  src/users/store/effects/users.effects.ts
  yarn.lock
Labels: ns:xui-mo-webapp-pr-344

#350 EUI-1002 functional test coverage
  Jenkinsfile_nightly
  package.json
  src/app/containers/header/header.component.ts
  test/e2e/config/common.conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/createOrganisation.feature
  test/e2e/features/app/endToend.feature
  test/e2e/features/app/inviteUser.feature
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/viewOrganisation.feature
  test/e2e/features/app/viewUser.feature
  test/e2e/features/pageObjects/approveOrganizationService.js
  test/e2e/features/pageObjects/createOrganisationObjects.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/inviteUserPage.js
  test/e2e/features/pageObjects/loginLogoutObjects.js
  test/e2e/features/pageObjects/mailinatorService.js
  test/e2e/features/pageObjects/viewOrganisationPage.js
  test/e2e/features/pageObjects/viewUserPage.js
  test/e2e/features/step_definitions/approveOrg.steps.js
  test/e2e/features/step_definitions/createOrganisation.steps.js
  test/e2e/features/step_definitions/headerPage.steps.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/viewOrganisation.steps.js
  test/e2e/features/step_definitions/viewUser.steps.js
  test/e2e/support/customWaits.js
  test/e2e/support/hooks.js
  test/e2e/support/timeout.js
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-350

#351 Tests/eui 1002 test coverage, fix branding to disable
  src/app/containers/header/header.component.ts
  test/e2e/config/common.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/features/app/endToend.feature
  test/e2e/features/app/inviteUser.feature
  test/e2e/features/pageObjects/approveOrganizationService.js
  test/e2e/features/pageObjects/createOrganisationObjects.js
  test/e2e/features/pageObjects/mailinatorService.js
  test/e2e/features/pageObjects/manageCasesService.js
  test/e2e/features/step_definitions/approveOrg.steps.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/viewOrganisation.steps.js
  test/e2e/features/step_definitions/viewUser.steps.js
  test/e2e/support/customWaits.js
Labels: ns:xui, rel:xui-mo-webapp-pr-351

#352 Tests/eui 1002 test coverage, added retry logic handle error/blank pages
  test/e2e/config/common.conf.js
  test/e2e/features/app/inviteUser.feature
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/inviteUserPage.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/viewOrganisation.steps.js
  test/e2e/features/step_definitions/viewUser.steps.js
  test/e2e/support/customWaits.js
  test/e2e/support/hooks.js
Labels: ns:xui, rel:xui-mo-webapp-pr-352

#354 Tests/eui 1002 test coverage, async function fix
  test/e2e/features/step_definitions/loginLogout.steps.js
Labels: ns:xui, rel:xui-mo-webapp-pr-354

#356 Tests/eui 1002 test coverage, fix to handle spinner
  test/e2e/features/app/viewOrganisation.feature
  test/e2e/features/app/viewUser.feature
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/viewOrganisation.steps.js
  test/e2e/features/step_definitions/viewUser.steps.js
  test/e2e/support/customWaits.js
Labels: ns:xui, rel:xui-mo-webapp-pr-356
