Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2020-04, with the labels that each got.

#455 Feature/eui 1644 already registered
  api/configuration/references.ts
  api/configuration/ui.ts
  api/configurationUI/index.ts
  charts/xui-mo-webapp/values.aat.template.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  src/app/containers/terms-and-conditions/terms-and-conditions.component.ts
  src/models/environmentConfig.model.ts
  src/register/containers/register/register.component.html
  src/register/containers/register/register.component.ts
  src/shared/services/environment.service.ts
  test/e2e/config/common.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/features/app/createOrganisation.feature
  test/e2e/features/pageObjects/createOrganisationObjects.js
  test/e2e/features/step_definitions/createOrganisation.steps.js
Labels: ns:xui, rel:xui-mo-webapp-pr-455

#438 Hotfix/missing pending names 2
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.html
Labels: ns:xui, rel:xui-mo-webapp-pr-438

#409 adding FPLA contact details to get help - release after 03-Mar
  src/app/app.constants.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-409

#449 EUI-1645 & EUI-1649 - combining 2 differents terms and conditions
  charts/xui-mo-webapp/values.preview.template.yaml
  src/app/app.constants.ts
  src/app/app.routes.ts
  src/app/components/index.ts
  src/app/components/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html
  src/app/components/legacy-terms-and-conditions/legacy-terms-and-conditions.component.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/components/terms-and-conditions/terms-and-conditions.component.spec.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.ts
  src/app/containers/index.ts
  src/app/containers/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.ts
  src/register/components/check-your-answers/check-your-answers.component.html
  src/register/components/check-your-answers/check-your-answers.component.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-449

#405 fix the missing PBA number when only 1 have 1 PBA number
  src/register/components/check-your-answers/check-your-answers.component.html
Labels: ns:xui, rel:xui-mo-webapp-pr-405

#448 EUI-1590 & EUI-1651 get help update contents
  src/app/app.constants.ts
  src/app/components/get-help/get-help.component.html
Labels: ns:xui, rel:xui-mo-webapp-pr-448

#463 Update mapping for error messages in registration
  api/tsconfig.json
  src/register/components/notification-banner/notification-banner.component.html
  src/register/mappings/apiErrorMappings.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-463

#381 EUI-1002: Test fixes and enhancements for failing tests in nightly build full f…
  test/e2e/config/common.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/features/app/inviteUser.feature
  test/e2e/features/app/termsAndConditions.feature
  test/e2e/features/app/viewUser.feature
  test/e2e/features/pageObjects/approveOrganizationService.js
  test/e2e/features/pageObjects/createOrganisationObjects.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/mailinatorService.js
  test/e2e/features/pageObjects/manageCasesService.js
  test/e2e/features/pageObjects/termsAndConditionsConfirmPage.js
  test/e2e/features/pageObjects/viewUserPage.js
  test/e2e/features/step_definitions/acceptTermsAndConditions.steps.js
  test/e2e/features/step_definitions/approveOrg.steps.js
  test/e2e/features/step_definitions/createOrganisation.steps.js
  test/e2e/features/step_definitions/dataSetUp.steps.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/viewUser.steps.js
  test/e2e/support/customWaits.js
Labels: ns:xui, rel:xui-mo-webapp-pr-381

#472 sourcemap support enabled
  api/server.ts
  api/webpack-node.config.js
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-472

#482 update redis chart
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/requirements.yaml
Labels: ns:xui, rel:xui-mo-webapp-pr-482

#459 Feature/eui 1524 &EUI 1525 reinvite user
  api/accounts/index.spec.ts
  api/inviteUser/index.ts
  api/inviteUser/inviteUserUtil.spec.ts
  api/inviteUser/inviteUserUtil.ts
  api/lib/payloadBuilder.spec.ts
  api/test/pact/pact-tests/test.spec.ts
  package.json
  src/app/components/service-down/service-down.component.html
  src/app/components/service-down/service-down.component.ts
  src/app/store/actions/app.actions.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/shared/components/hmcts-error-summary/hmcts-error-summary.component.html
  src/shared/components/hmcts-error-summary/hmcts-error-summary.component.ts
  src/shared/components/hmcts-main-wrapper/hmcts-main-wrapper.component.html
  src/shared/components/hmcts-main-wrapper/hmcts-main-wrapper.component.ts
  src/users/components/invite-user-form/invite-user-form.component.html
  src/users/containers/invite-user/invite-user.component.html
  src/users/containers/invite-user/invite-user.component.spec.ts
  src/users/containers/invite-user/invite-user.component.ts
  src/users/containers/user-details/user-details.component.html
  src/users/containers/user-details/user-details.component.spec.ts
  src/users/containers/user-details/user-details.component.ts
  src/users/containers/users/users.component.html
  src/users/containers/users/users.component.ts
  src/users/models/errorReport.model.ts
  src/users/models/userform.model.ts
  src/users/store/actions/invite-user.actions.ts
  src/users/store/actions/user.actions.ts
  src/users/store/effects/invite-user.effects.spec.ts
  src/users/store/effects/invite-user.effects.ts
  src/users/store/effects/users.effects.spec.ts
  src/users/store/effects/users.effects.ts
  src/users/store/reducers/invite-user.reducer.ts
  src/users/store/reducers/users.reducer.spec.ts
  src/users/store/reducers/users.reducer.ts
  src/users/store/selectors/user.selectors.spec.ts
  src/users/store/selectors/user.selectors.ts
  src/users/users.module.ts
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-459

#484 logger message for the Re-Invite and invite
  src/users/models/userform.model.ts
  src/users/store/effects/invite-user.effects.spec.ts
  src/users/store/effects/invite-user.effects.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-484

#486 Feature/eui 1524 reinvite user - Bug fixes
  src/app/components/service-down/service-down.component.html
  src/app/components/service-down/service-down.component.spec.ts
  src/app/components/service-down/service-down.component.ts
  src/app/store/reducers/app.reducer.ts
  src/users/containers/invite-user/invite-user.component.ts
  src/users/store/actions/invite-user.actions.ts
  src/users/store/effects/invite-user.effects.spec.ts
  src/users/store/effects/invite-user.effects.ts
  src/users/store/reducers/invite-user.reducer.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-486

#488 Accessibility text update.
  src/app/components/accessibility/accessibility.component.html
Labels: ns:xui, rel:xui-mo-webapp-pr-488

#451 crossbrowser_test_EUI-602
  package.json
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/crossbrowser.conf_old.js
  test/e2e/features/app/endToend.feature
  test/e2e/features/app/inviteUser.feature
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/viewOrganisation.feature
  test/e2e/support/hooks.js
Labels: ns:xui, rel:xui-mo-webapp-pr-451

#489 Add extra error handling as per eui-1591
  src/register/components/check-your-answers/check-your-answers.component.html
  src/register/components/check-your-answers/check-your-answers.component.ts
  src/register/mappings/apiErrorMappings.ts
  src/register/store/actions/registration.actions.ts
  src/register/store/reducers/registration.reducer.ts
  src/register/store/selectors/registration.selectors.ts
  src/styles.scss
  test/e2e/support/hooks.js
Labels: ns:xui, rel:xui-mo-webapp-pr-489

#479 Feature/eui 1686 global tokens
  api/accounts/accountUtil.ts
  api/accounts/index.ts
  api/application.ts
  api/auth/index.ts
  api/auth/serviceToken.ts
  api/customTypings/express/index.d.ts
  api/editUserPermissions/index.ts
  api/getUserTermsAndConditions/index.ts
  api/healthCheck/index.ts
  api/inviteUser/index.ts
  api/lib/http.ts
  api/lib/interceptors.ts
  api/lib/payloadBuilder.spec.ts
  api/lib/s2sTokenGeneration.ts
  api/lib/util.ts
  api/organisation/index.ts
  api/payments/index.ts
  api/postUserTermsAndConditions/index.ts
  api/register-org/index.ts
  api/services/idam.ts
  api/services/payment.ts
  api/services/rdProfessional.ts
  api/services/serviceAuth.spec.ts
  api/services/serviceAuth.ts
  api/suspendUser/index.ts
  api/termsAndConditions/index.ts
  api/tsconfig.json
  api/userList/index.ts
  package.json
  test/e2e/config/common.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/features/app/endToend.feature
  test/e2e/features/app/inviteUser.feature
  test/e2e/features/app/termsAndConditions.feature
  test/e2e/features/app/viewUser.feature
  test/e2e/features/pageObjects/approveOrganizationService.js
  test/e2e/features/pageObjects/manageCasesService.js
  test/e2e/features/pageObjects/termsAndConditionsConfirmPage.js
  test/e2e/features/step_definitions/acceptTermsAndConditions.steps.js
  test/e2e/features/step_definitions/dataSetUp.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/support/timeout.js
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-479

#491 ScreenshotUtil issue fix
  test/e2e/features/pageObjects/approveOrganizationService.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/viewOrganisation.steps.js
  test/e2e/features/step_definitions/viewUser.steps.js
  test/e2e/support/hooks.js
Labels: ns:xui, rel:xui-mo-webapp-pr-491
