Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2020-06, with the labels that each got.

#510 Update privacy policy with latest version
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/privacy-policy/privacy-policy.component.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-510

#503 Feature/eui 1883 ui timeout dev
  README.md
  api/.env.defaults
  api/auth/index.ts
  api/configuration/references.ts
  api/user/index.ts
  api/user/user.ts
  api/user/userTimeout.spec.ts
  api/user/userTimeout.ts
  config/custom-environment-variables.json
  config/default.json
  package-lock.json
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/index.ts
  src/app/components/signed-out/signed-out.component.html
  src/app/components/signed-out/signed-out.component.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effects.spec.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/user-profile/models/user.model.ts
  src/user-profile/store/effects/user-profile.effects.ts
  src/user-profile/store/effects/user.effects.spec.ts
  src/user-profile/store/reducers/user-profile.reducer.spec.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-503

#514 EUI-2067: Refactor scenario with actions to invite user.
  Jenkinsfile_nightly
  test/e2e/config/common.conf.js
  test/e2e/features/app/endToend.feature
  test/e2e/features/app/inviteUser.feature
  test/e2e/features/app/termsAndConditions.feature
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/manageCasesService.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
Labels: ns:xui, rel:xui-mo-webapp-pr-514

#516 Feature/eui 1960 restyle signout button
  package.json
  src/app/containers/app/app.component.html
  src/styles.scss
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-516

#518 Release eui 2100 master
  Jenkinsfile_nightly
  api/accounts/index.spec.ts
  api/inviteUser/index.ts
  api/inviteUser/inviteUserUtil.spec.ts
  api/inviteUser/inviteUserUtil.ts
  api/lib/payloadBuilder.spec.ts
  api/test/pact/pact-tests/test.spec.ts
  package.json
  src/app/components/service-down/service-down.component.html
  src/app/components/service-down/service-down.component.spec.ts
  src/app/components/service-down/service-down.component.ts
  src/app/store/actions/app.actions.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/selectors/app.selectors.ts
  src/shared/components/hmcts-error-summary/hmcts-error-summary.component.html
  src/shared/components/hmcts-error-summary/hmcts-error-summary.component.ts
  src/shared/components/hmcts-main-wrapper/hmcts-main-wrapper.component.html
  src/shared/components/hmcts-main-wrapper/hmcts-main-wrapper.component.ts
  src/users/components/invite-user-form/invite-user-form.component.html
  src/users/containers/invite-user/invite-user.component.html
  src/users/containers/invite-user/invite-user.component.spec.ts
  src/users/containers/invite-user/invite-user.component.ts
  src/users/containers/user-details/user-details.component.html
  src/users/containers/user-details/user-details.component.spec.ts
  src/users/containers/user-details/user-details.component.ts
  src/users/containers/users/users.component.html
  src/users/containers/users/users.component.ts
  src/users/models/errorReport.model.ts
  src/users/models/userform.model.ts
  src/users/store/actions/invite-user.actions.ts
  src/users/store/actions/user.actions.ts
  src/users/store/effects/invite-user.effects.spec.ts
  src/users/store/effects/invite-user.effects.ts
  src/users/store/effects/users.effects.spec.ts
  src/users/store/effects/users.effects.ts
  src/users/store/reducers/invite-user.reducer.ts
  src/users/store/reducers/users.reducer.spec.ts
  src/users/store/reducers/users.reducer.ts
  src/users/store/selectors/user.selectors.spec.ts
  src/users/store/selectors/user.selectors.ts
  src/users/users.module.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-518

#520 missing commits for 409 error
  src/users/containers/invite-user/invite-user.component.ts
  src/users/store/reducers/invite-user.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-520

#522 add stalebot
  .github/stale.yml
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-522

#519 TESTS: refactored configuration and enabled mutation tests for node.
  api/package.json
  api/stryker.node.conf.js
  package.json
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/termsAndConditionsConfirmPage.js
  test/e2e/features/step_definitions/acceptTermsAndConditions.steps.js
  test/e2e/features/step_definitions/createOrganisation.steps.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/viewOrganisation.steps.js
  test/e2e/features/step_definitions/viewUser.steps.js
  test/e2e/support/customWaits.js
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-519
