Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2020-02, with the labels that each got.

#361 Feature/eui 1439 transactions screen
  api/lib/config/environments/preview.config.ts
  api/lib/tunnel.ts
  api/services/serviceAuth.ts
  charts/xui-mo-webapp/Chart.yaml
  package.json
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.html
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.ts
  src/app/app.constants.ts
  src/app/store/reducers/app.reducer.spec.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/fee-accounts/components/summary/summary.component.html
  src/fee-accounts/components/summary/summary.component.ts
  src/fee-accounts/containers/account-overview/account-overview.component.html
  src/fee-accounts/containers/account-summary/account-summary.component.html
  src/fee-accounts/containers/account-transactions/account-transactions.component.html
  src/fee-accounts/containers/account-transactions/account-transactions.component.spec.ts
  src/fee-accounts/containers/account-transactions/account-transactions.component.ts
  src/fee-accounts/fee-accounts.module.ts
  src/fee-accounts/guards/accounts.guard.ts
  src/shared/components/custom-pipe/date-pipe-with-to.ts
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-361

#362 change the header/title EUI-1339, EUI-1473, EUI-1474 - HOTFIX
  src/app/app.constants.ts
  src/register/constants/emailAddress.ts
  src/register/containers/register/register.component.html
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/step_definitions/loginLogout.steps.js
Labels: ns:xui, rel:xui-mo-webapp-pr-362

#369 Bug/eui 1470 duplicate email error - HOTFIX
  src/users/store/reducers/invite-user.reducer.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-369

#340 adding get help and update gethelp EUI-1444
  package.json
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/get-help/get-help.component.html
  src/app/components/get-help/get-help.component.spec.ts
  src/app/components/get-help/get-help.component.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/index.ts
  src/app/containers/app/app.component.ts
  yarn.lock
Labels: ns:xui, ns:xui-mo-webapp-pr-340, rel:xui-mo-webapp-pr-340

#371 Hotfix/eui 1500 1501 terms accessibility content
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.spec.ts
  src/app/components/accessibility/accessibility.component.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
Labels: ns:xui, rel:xui-mo-webapp-pr-371

#370 Update Polyfills.ts
  src/polyfills.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-370

#374 Hotfix/1500 minor fixes
  src/app/components/accessibility/accessibility.component.html
Labels: ns:xui, rel:xui-mo-webapp-pr-374

#379 fixing the linting issue
  src/fee-accounts/components/notifications/fee-account-error-notification.component.ts
  src/fee-accounts/containers/account-missing/account-missing.component.ts
  src/fee-accounts/containers/overview-container/account-overview-container.component.html
  src/fee-accounts/containers/overview-container/account-overview-container.component.ts
  src/fee-accounts/containers/overview/account-overview.component.html
  src/users/containers/edit-user-permissions/edit-user-permission.component.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-379

#380 Feature/merge master into develop 13th feb
  Jenkinsfile_CNP
  package.json
  sonar-project.properties
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.spec.ts
  src/app/components/accessibility/accessibility.component.ts
  src/app/components/get-help/get-help.component.html
  src/app/components/get-help/get-help.component.spec.ts
  src/app/components/get-help/get-help.component.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/index.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/app/app.component.ts
  src/polyfills.ts
  src/register/constants/emailAddress.ts
  src/register/containers/register/register.component.html
  src/users/store/reducers/invite-user.reducer.ts
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-380

#382 Feature/eui 1492 reduce docker
  Dockerfile
  Jenkinsfile_CNP
  api/.env.defaults
  api/.env.example
  api/accounts/index.ts
  api/auth/index.ts
  api/auth/serviceToken.ts
  api/configuration/constants.ts
  api/configuration/health.ts
  api/configuration/index.ts
  api/configuration/references.ts
  api/configuration/ui.ts
  api/healthCheck/index.ts
  api/interfaces/environment.config.ts
  api/inviteUser/index.ts
  api/jurisdictions/index.ts
  api/lib/appInsights.ts
  api/lib/interceptors.ts
  api/lib/log4jui.ts
  api/lib/serviceToken.ts
  api/lib/stack.ts
  api/lib/stateEngine.ts
  api/lib/tunnel.ts
  api/local.ts
  api/monitoring-tools/index.ts
  api/organisation/index.ts
  api/package.json
  api/payments/index.ts
  api/register-org/index.ts
  api/server.ts
  api/services/idam.ts
  api/services/payment.ts
  api/services/rdProfessional.ts
  api/services/serviceAuth.spec.ts
  api/services/serviceAuth.ts
  api/userList/index.ts
  api/webpack-node.config.js
  charts/xui-mo-webapp/values.aat.template.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package-lock.json
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-382

#383 using new config for the missing endpoints
  api/editUserPermissions/index.ts
  api/lib/appInsights.ts
  api/suspendUser/index.ts
  api/userList/index.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-383

#360 Add CSP configuration files
  src/web.config
  web.config
Labels: ns:xui, rel:xui-mo-webapp-pr-360

#388 handling T&C service gracefully when unavailable
  api/healthCheck/index.ts
  src/accept-tc/store/effects/acept-tc.effects.ts
  src/app/app.routes.ts
  src/app/store/effects/app.effects.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-388

#384 document readme changes
  README.md
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.yaml
Labels: ns:xui, rel:xui-mo-webapp-pr-384

#395 functional test username change to autotest_superuser@mailinator.com
  test/e2e/config/common.conf.js
Labels: ns:xui, rel:xui-mo-webapp-pr-395

#396 user name changes
  test/e2e/config/fullfunctional.conf.js
  test/e2e/features/app/inviteUser.feature
  test/integration/tests/utils/getToken.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-396

#398 Feature/eui 1566 upgrade typescript
  package-lock.json
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-398

#399 PR for the upgrade of Node, Typescript and Angular
  package-lock.json
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-mo-webapp-pr-399

#400 node version 12.13.0
  .nvrmc
  infrastructure/main.tf
  package.json
Labels: ns:xui, rel:xui-mo-webapp-pr-400

#403 Add urls to values.yaml file.
  api/configuration/health.ts
  api/configuration/references.ts
  api/configuration/ui.ts
  api/interfaces/environment.config.ts
  api/local.ts
  api/server.ts
  charts/xui-mo-webapp/values.aat.template.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  sonar-project.properties
Labels: ns:xui, rel:xui-mo-webapp-pr-403

#404 Config clean up
  api/configuration/health.ts
  api/configuration/references.ts
  api/configuration/ui.ts
  api/interfaces/environment.config.ts
  api/local.ts
  api/server.ts
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/requirements.yaml
  charts/xui-mo-webapp/values.aat.template.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  sonar-project.properties
Labels: ns:xui, rel:xui-mo-webapp-pr-404

#426 Remove health from server.ts
  api/server.ts
Labels: ns:xui, rel:xui-mo-webapp-pr-426
