Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2020-09, with the labels that each got.

#569 hotfix auth redirect, session timeout
  api/auth/index.ts
  api/interfaces/environment.config.ts
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  src/user-profile/guards/auth.guard.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-569

#571 tests/nightly build fix
  Jenkinsfile_nightly
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-571

#572 remove pui-caa role for Invite User
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-572

#573 EUI-2625-accessibility-policy
  Jenkinsfile_nightly
  package.json
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-573

#576 no email/userId in oauth2 flow fix
  api/auth/index.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-576
