Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2020-10, with the labels that each got.

#579 MO terraform upgrade
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-579

#581 EUI2780_CB_SecurityFix
  audit.json
  security.sh
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/crossbrowser.conf_old.js
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-581

#584 EUI-2800 mutation test fixes
  api/configuration/index.spec.ts
  api/configurationUI/index.spec.ts
  api/inviteUser/inviteUserUtil.spec.ts
  api/lib/log4jui.spec.ts
  api/organisation/index.spec.ts
  audit.json
  package.json
  stryker.node.conf.js
  test/e2e/features/pageObjects/mailinatorService.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/support/hooks.js
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-584
