Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2021-06, with the labels that each got.

#649 EUI-2109
  src/app/app.constants.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.scss
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/models/app-titles.model.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-649

#676 editpermissionstests_EUI-1622
  test/e2e/config/common.conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/features/app/editPermissions.feature
  test/e2e/features/pageObjects/inviteUserPage.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
Labels: ns:xui, prd:xui, qa/automation, rel:xui-mo-webapp-pr-676

#673 EUI-3707-optimize-es-query
  api/unassignedCases/index.ts
  api/unassignedCases/unassingedCases-util.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-673, stale

#615 EUI 2645 no need to send jurisdictions to prd
  api/lib/payloadBuilder.ts
  src/app/app.module.ts
  src/register/containers/register/register.component.ts
  src/users/containers/invite-user/invite-user.component.ts
  src/users/models/userform.model.ts
  src/users/store/effects/invite-user.effects.spec.ts
  test/e2e/features/pageObjects/viewUserPage.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/integration/tests/post_Invite_User.ts
  test/integration/tests/post_ReInvite_User.ts
  test/integration/tests/post_register_org.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-615

#698 EXUI_MO_3.0.27d_3.0.28
  README.md
  api/lib/payloadBuilder.ts
  projects/gov-ui/src/lib/components/gov-uk-checkbox/gov-uk-checkbox.component.ts
  projects/gov-ui/src/lib/components/gov-uk-label/gov-uk-label.component.ts
  src/app/app.module.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/organisation/containers/organisation/organisation.component.html
  src/register/components/check-your-answers/check-your-answers.component.html
  src/register/constants/haveDx.ts
  src/register/constants/organisationAddress.ts
  src/register/constants/organisationDx.ts
  src/register/constants/organisationHaveSra.ts
  src/register/constants/pbaNumber.ts
  src/register/constants/sraNumber.ts
  src/register/containers/hmcts-form-builder/src/lib/components/fieldset/fieldset.component.html
  src/register/containers/hmcts-form-builder/src/lib/components/form-builder/form-builder.component.html
  src/register/containers/hmcts-form-builder/src/lib/components/form-builder/form-builder.component.ts
  src/register/containers/hmcts-form-builder/src/lib/components/jui-form-elements/jui-form-elements.component.html
  src/register/containers/register/register.component.ts
  src/users/components/invite-user-permissions/invite-user-permission.component.html
  src/users/containers/invite-user-success/invite-user-success.component.html
  src/users/containers/invite-user/invite-user.component.ts
  src/users/models/userform.model.ts
  src/users/store/effects/invite-user.effects.spec.ts
  test/accessibility/tests/unauthenticatedUrls.js
  test/e2e/features/pageObjects/createOrganisationObjects.js
  test/e2e/features/pageObjects/viewUserPage.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/integration/tests/post_Invite_User.ts
  test/integration/tests/post_ReInvite_User.ts
  test/integration/tests/post_register_org.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-698

#700 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-700
