Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2021-08, with the labels that each got.

#710 Add CVEs to known list
  test/e2e/config/crossbrowser.conf.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-710

#650 EUI-2124-Unlabelled Form Fields
  src/register/constants/emailAddress.ts
  src/register/constants/oganisationName.ts
  src/register/constants/organisationAddress.ts
  src/register/constants/sraNumber.ts
  test/integration/tests/utils/getCookie.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-650

#656 EUI-2134-Status Message
  src/register/containers/register/register.component.ts
  src/register/store/reducers/registration.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-656

#551 Add link purpose
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/tests/unauthenticatedUrls.js
  test/e2e/features/step_definitions/loginLogout.steps.js
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-551

#713 Merge-release-to-master-rd
  src/app/app-initializer.ts
  src/app/components/cookie-policy/cookie-policy-component.spec.ts
  src/app/components/cookie-policy/cookie-policy.component.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/register/constants/emailAddress.ts
  src/register/constants/oganisationName.ts
  src/register/constants/organisationAddress.ts
  src/register/constants/sraNumber.ts
  src/register/containers/register/register.component.ts
  src/register/store/reducers/registration.reducer.ts
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/tests/unauthenticatedUrls.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/integration/tests/utils/getCookie.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-713
