Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2021-05, with the labels that each got.

#681 added additional yarn known issues
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-681

#683 Xui disable auto scaler
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.yaml
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-683

#690 added all cves to file
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-690

#693 feat:Add civil roles for inviting org members
  src/app/app.constants.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-693

#694 crossbrowser fix for MO
  package.json
  test/e2e/config/crossbrowser.conf.js
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-694
