Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2021-12, with the labels that each got.

#743 Update known issue list
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-743

#745 Upgrade node-gyp
  .nvrmc
  package.json
  test/accessibility/helpers/pa11yUtil.js
  test/e2e/features/step_definitions/createOrganisation.steps.js
  test/e2e/support/customWaits.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-745

#733 Move page titles from ngrx store to routes/ title service
  src/app/app.routes.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/store/actions/app.actions.ts
  src/app/store/effects/app.effects.spec.ts
  src/app/store/effects/app.effects.ts
  src/app/store/reducers/app.reducer.spec.ts
  src/app/store/reducers/app.reducer.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/store/selectors/app.selectors.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/organisation/organisation.routing.ts
  src/register/register.routing.ts
  src/style-guide/style-guide.routing.ts
  src/unassigned-cases/unassigned-cases.routing.ts
  src/user-profile/userProfile.routing.ts
  src/users/users.routing.ts
Labels: dependencies, ns:xui, prd:xui, rel:xui-mo-webapp-pr-733

#744 Upgrade node basechart
  charts/xui-mo-webapp/Chart.yaml
  sonar-project.properties
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-744
