Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2021-11, with the labels that each got.

#728 changed common lib version
  package.json
  src/accept-tc/accept-tc.module.ts
  src/app/app.module.ts
  src/app/containers/app/app.component.ts
  src/users/users.module.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-728

#735 cve-supression
  test/integration/tests/get_Organisation_Details.ts
  test/integration/tests/utils/getCookie.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-735

#712 Add syncBranchesWithMaster to Jenkins config
  Jenkinsfile_CNP
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-712

#741 Update known issue list for CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-741

#742 Upgrade properties-volume
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-742
