Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2021-02, with the labels that each got.

#612 EUI-3152-toggle-CCA-access-role
  src/users/components/invite-user-permissions/invite-user-permission.component.html
  src/users/components/invite-user-permissions/invite-user-permission.component.spec.ts
  src/users/components/invite-user-permissions/invite-user-permission.component.ts
  src/users/containers/edit-user-permissions/edit-user-permission.component.html
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-612

#616 Unassinged cases feature toggle issue
  src/app/app-initializer.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-616

#623 EUI-3132-CAA-content-changes
  package.json
  src/unassigned-cases/containers/unassigned-cases/unassigned-cases.component.html
  src/users/components/invite-user-permissions/invite-user-permission.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-623

#626 Helm infra upgrade
  Jenkinsfile_nightly
  README.md
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/requirements.yaml
  charts/xui-mo-webapp/values.yaml
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/test_config.tf
  infrastructure/variables.tf
  package.json
  test/e2e/config/crossbrowser.conf.js
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-626

#629 EUI-3369-content-change-unshare-case
  src/unassigned-cases/containers/case-share-complete/case-share-complete.component.html
  src/unassigned-cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/unassigned-cases/containers/case-share-complete/case-share-complete.component.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-629

#624 EUI-3362-share-case-remove-user: for manage organisation
  api/caseshare/dtos/user-dto.ts
  api/caseshare/models/case-share.model.ts
  api/caseshare/models/ccd-raw-user.model.ts
  api/caseshare/models/unassigned-case.model.ts
  api/caseshare/models/user-details.model.ts
  api/caseshare/real-api.ts
  api/common/crudService.ts
  config/default.json
  src/unassigned-cases/containers/case-share-complete/case-share-complete.component.html
  src/unassigned-cases/containers/case-share-complete/case-share-complete.component.scss
  src/unassigned-cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/unassigned-cases/containers/case-share-complete/case-share-complete.component.ts
  src/unassigned-cases/containers/case-share/case-share.component.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-624

#625 Ta 410 fix pact publish
  Jenkinsfile_CNP
  README.md
  api/configuration/references.ts
  api/test/pact/pact-tests/feePayApi/getAccounts.spec.ts
  api/test/pact/pact-tests/idamApi/getUserDetails.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/editUserPermissions.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/getOrganisationByEmailId.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/getOrganisationDetails.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/inviteUserPost.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/registerOrgPostExternal.spec.ts
  api/test/pact/pact-tests/rdProfessionalApi/suspendUser.spec.ts
  api/test/pact/pact-tests/settings/provider.mock.ts
  api/test/pact/publish/publish.js
  api/test/pact/publish/publish.ts
  config/default.json
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-625
