Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2021-03, with the labels that each got.

#614 Add service message banner to the application
  package.json
  src/app/app.constants.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.ts
  src/shared/services/session-storage.service.ts
  src/user-profile/services/auth.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-614

#632 Manage Organisation doesn't work on IE11
  package.json
  src/polyfills.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-632

#638 resolved cve issues
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-638
