Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2022-08, with the labels that each got.

#892 CVE
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-892

#893 CVE fixes
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-893

#894 cve fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-894

#899 CVE/16 08 2022
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-899

#900  EUI-6579 : nodeMock port conflict fix with availability port check 
  Jenkinsfile_nightly
  angular.json
  package.json
  proxyTest.config.json
  test/accessibility/config/protractor.conf.js
  test/nodeMock/app.js
  test/nodeMock/availablePortFinder.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-900

#901 cve
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-901

#898 EUI-6547: CAA cases filter component refactor
  package.json
  src/caa-cases/components/caa-filter-assigned/caa-filter-assigned.component.spec.ts
  src/caa-cases/components/caa-filter-unassigned/caa-filter-unassigned.component.html
  src/caa-cases/components/caa-filter-unassigned/caa-filter-unassigned.component.scss
  src/caa-cases/components/caa-filter-unassigned/caa-filter-unassigned.component.spec.ts
  src/caa-cases/components/caa-filter-unassigned/caa-filter-unassigned.component.ts
  src/caa-cases/components/caa-filter/caa-filter.component.html
  src/caa-cases/components/caa-filter/caa-filter.component.scss
  src/caa-cases/components/caa-filter/caa-filter.component.spec.ts
  src/caa-cases/components/caa-filter/caa-filter.component.ts
  src/caa-cases/components/index.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.html
  src/caa-cases/containers/caa-cases/caa-cases.component.ts
  src/caa-cases/models/caa-cases.enum.ts
  src/caa-cases/services/caa-cases.service.spec.ts
  src/caa-cases/store/actions/caa-cases.actions.spec.ts
  src/caa-cases/store/effects/caa-cases.effects.spec.ts
  src/caa-cases/store/effects/caa-cases.effects.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-898

#904 Add backstage configuration file
  catalog-info.yaml
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-904

#888 EUI-6345 CAA unassigned cases filter
  angular.json
  api/application.ts
  api/caaCases/caaCases.util.ts
  api/caaCases/enums/index.ts
  api/caaCases/index.ts
  api/lib/appInsights.spec.ts
  api/lib/appInsights.ts
  catalog-info.yaml
  package.json
  proxyTest.config.json
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/caa-cases/caa-cases.module.ts
  src/caa-cases/caa-cases.routing.ts
  src/caa-cases/components/caa-filter/caa-filter.component.html
  src/caa-cases/components/caa-filter/caa-filter.component.scss
  src/caa-cases/components/caa-filter/caa-filter.component.spec.ts
  src/caa-cases/components/caa-filter/caa-filter.component.ts
  src/caa-cases/components/index.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.html
  src/caa-cases/containers/caa-cases/caa-cases.component.scss
  src/caa-cases/containers/caa-cases/caa-cases.component.spec.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.ts
  src/caa-cases/models/caa-cases.enum.ts
  src/caa-cases/models/caa-cases.model.ts
  src/caa-cases/services/caa-cases.service.spec.ts
  src/caa-cases/services/caa-cases.service.ts
  src/caa-cases/store/actions/caa-cases.actions.spec.ts
  src/caa-cases/store/actions/caa-cases.actions.ts
  src/caa-cases/store/effects/caa-cases.effects.spec.ts
  src/caa-cases/store/effects/caa-cases.effects.ts
  src/caa-cases/store/selectors/share-case.selectors.spec.ts
  src/caa-cases/util/caa-cases.util.spec.ts
  src/caa-cases/util/caa-cases.util.ts
  test/accessibility/config/protractor.conf.js
  test/nodeMock/app.js
  test/nodeMock/availablePortFinder.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, pinned, rel:xui-mo-webapp-pr-888

#906 CVE temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-906
