Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2022-09, with the labels that each got.

#890 Tests/caa assigned cases pa11y
  test/accessibility/tests/UnassignedCases.js
  test/nodeMock/reqResMapping.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-890

#908 fix to address duplicate users and org.
  test/integration/tests/post_Invite_User.ts
  test/integration/tests/post_register_org.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-908

#913 EUI-5021 CAA all assignee filter
  api/caaCaseTypes/caaCaseTypes.util.spec.ts
  api/caaCaseTypes/caaCaseTypes.util.ts
  api/caaCaseTypes/index.ts
  api/caaCases/caaCases.util.spec.ts
  src/caa-cases/components/caa-filter/caa-filter.component.scss
  src/caa-cases/containers/caa-cases/caa-cases.component.html
  src/caa-cases/containers/caa-cases/caa-cases.component.scss
  src/caa-cases/containers/caa-cases/caa-cases.component.ts
  src/caa-cases/services/caa-cases.service.spec.ts
  src/caa-cases/services/caa-cases.service.ts
  src/caa-cases/store/actions/caa-cases.actions.spec.ts
  src/caa-cases/store/actions/caa-cases.actions.ts
  src/caa-cases/store/effects/caa-cases.effects.spec.ts
  src/caa-cases/store/effects/caa-cases.effects.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-913

#915 EUI-3966: Share Case web component UI changes
  package.json
  src/app/store/reducers/index.ts
  src/caa-cases/containers/case-share/case-share.component.html
  src/caa-cases/containers/case-share/case-share.component.ts
  src/caa-cases/store/effects/share-case.effects.spec.ts
  src/caa-cases/store/effects/share-case.effects.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-915

#916 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-916

#918 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-918

#917 EUI-5478 CAA Assigned cases null and unhappy path
  src/caa-cases/components/caa-filter/caa-filter.component.html
  src/caa-cases/components/caa-filter/caa-filter.component.spec.ts
  src/caa-cases/components/caa-filter/caa-filter.component.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.html
  src/caa-cases/containers/caa-cases/caa-cases.component.scss
  src/caa-cases/containers/caa-cases/caa-cases.component.spec.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.ts
  src/caa-cases/models/caa-cases.enum.ts
  src/caa-cases/util/caa-cases.util.spec.ts
  src/caa-cases/util/caa-cases.util.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-917

#923 EUI-6577: Share Case web component UI changes
  package.json
  src/caa-cases/containers/case-share/case-share.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-923

#922 EUI-6813 CAA filter no cases found message
  api/caaCaseTypes/caaCaseTypes.util.spec.ts
  api/caaCaseTypes/caaCaseTypes.util.ts
  api/caaCaseTypes/index.ts
  api/caaCases/caaCases.util.ts
  config/default.json
  src/caa-cases/containers/caa-cases/caa-cases.component.html
  src/caa-cases/containers/caa-cases/caa-cases.component.spec.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.ts
  src/caa-cases/services/caa-cases.service.spec.ts
  src/caa-cases/services/caa-cases.service.ts
  src/caa-cases/store/actions/caa-cases.actions.spec.ts
  src/caa-cases/store/actions/caa-cases.actions.ts
  src/caa-cases/store/effects/caa-cases.effects.spec.ts
  src/caa-cases/store/effects/caa-cases.effects.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-922

#930 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-930
