Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2022-01, with the labels that each got.

#748 Upgrade healthcheck
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-748

#751 CVE temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-751

#757 CVE temp1
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-757

#759 cve supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-759

#763 cve supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-763

#764 Add CVEs to known list
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-764
