Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2022-07, with the labels that each got.

#865 Update redis Chart Config
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-865

#869 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-869

#870 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-870

#871 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-871

#873 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-873

#876 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-876

#877 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-877

#881 Upgrade node basechart
  charts/xui-mo-webapp/Chart.yaml
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-881

#886 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-886

#882 remove telemetry api call for requests
  api/application.ts
  api/lib/appInsights.spec.ts
  api/lib/appInsights.ts
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-882
