Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2022-04, with the labels that each got.

#815 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-815

#821 CVE tmp fix7
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-821

#824 Added NFD to default.json caseTypes
  config/default.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-824

#823 E UI 5675 allow pba to be created in mo
  api/configuration/references.ts
  api/pbas/index.ts
  api/register-org/index.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/organisation/containers/organisation/organisation.component.html
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-823

#827 CVEs temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-827

#828 CVEs temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-828

#830 implementation
  api/pbas/index.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-830

#831 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-831

#832 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-832
