Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2022-02, with the labels that each got.

#766 MO enable fortify on nightly
  Jenkinsfile_nightly
  package.json
  test/java/.gitignore
  test/java/build.gradle
  test/java/config/fortify-client.properties
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
  test/java/settings.gradle
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-766

#768 CVE Supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-768

#775 cve suppresion
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-775

#776 cve suppresion
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-776

#777 Upgrade node base chart to 2.4.0
  charts/xui-mo-webapp/Chart.yaml
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-777

#785 CVEs tempfix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-785
