Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2022-10, with the labels that each got.

#929 EUI-6754 CAA unassigned cases reset filter
  src/caa-cases/components/caa-filter/caa-filter.component.html
  src/caa-cases/components/caa-filter/caa-filter.component.spec.ts
  src/caa-cases/components/caa-filter/caa-filter.component.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.html
  src/caa-cases/containers/caa-cases/caa-cases.component.spec.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.ts
  src/caa-cases/models/caa-cases.enum.ts
  src/caa-cases/models/caa-cases.model.ts
  src/caa-cases/services/caa-cases.service.spec.ts
  src/caa-cases/services/caa-cases.service.ts
  src/caa-cases/store/selectors/share-case.selectors.spec.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-929

#936 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-936

#935 EUI-6546 CAA assignee filter text box styling
  src/caa-cases/components/caa-filter/caa-filter.component.scss
  src/caa-cases/components/caa-filter/caa-filter.component.spec.ts
  src/caa-cases/util/caa-cases.util.spec.ts
  src/caa-cases/util/caa-cases.util.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-935

#937 EUI-6731: Case Share success page content changes
  package.json
  src/caa-cases/containers/case-share-complete/case-share-complete.component.html
  src/caa-cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/caa-cases/containers/case-share-complete/case-share-complete.component.ts
  src/caa-cases/containers/case-share-confirm/case-share-confirm.component.spec.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-937

#939 EUI-6893: Case Share confirmation page - back link
  src/caa-cases/containers/case-share-confirm/case-share-confirm.component.spec.ts
  src/caa-cases/containers/case-share-confirm/case-share-confirm.component.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-939

#940 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-940

#942 cve tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-942

#943 EUI-6920 CAA Assignee name filter validation problem
  src/caa-cases/util/caa-cases.util.spec.ts
  src/caa-cases/util/caa-cases.util.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-943

#946 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-946
