Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2022-05, with the labels that each got.

#834 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-834

#836 implementation and audit command
  src/register/constants/organisationAddress.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-836

#837 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-837

#840 Update CVEs list
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-840

#841 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-841

#842 EUI-5817-avoiding roles returned due to performance issue
  api/caseshare/real-api.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-842

#847 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-847
