Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2023-03, with the labels that each got.

#975 ported over correct styling and upgraded govuk_toolkit
  package.json
  src/app/containers/app/app.component.scss
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-975

#921 EUI-6728 MO api tests fixing
  api/allUserList/index.spec.ts
  api/allUserListWithoutRoles/index.spec.ts
  api/common/crudService.spec.ts
  api/inviteUser/index.spec.ts
  api/monitoring-tools/index.spec.ts
  api/monitoring-tools/index.ts
  api/refdataUserCommonUrlUtil.spec.ts
  api/refdataUserUrlUtil.spec.ts
  api/suspendUser/index.spec.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-921

#988 EUI-7685 CAA display message when service has not configured the org cases view for a case type
  README.md
  charts/xui-mo-webapp/Chart.yaml
  src/caa-cases/containers/caa-cases/caa-cases.component.html
  src/caa-cases/containers/caa-cases/caa-cases.component.spec.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.ts
  src/caa-cases/store/actions/caa-cases.actions.spec.ts
  src/caa-cases/store/actions/caa-cases.actions.ts
  src/caa-cases/store/effects/caa-cases.effects.ts
  src/caa-cases/store/reducers/caa-cases.reducer.spec.ts
  src/caa-cases/store/reducers/caa-cases.reducer.ts
  src/caa-cases/store/selectors/caa-cases.selector.spec.ts
  src/caa-cases/store/selectors/caa-cases.selector.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-988

#934 EUI-6255 optional text added
  src/register/constants/organisationDx.ts
  src/register/constants/pbaNumber.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-934

#919 EUI-6253
  src/register/containers/register/register.component.html
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-919

#925 EUI-4697
  src/accept-tc/containers/accept-tc-wrapper.component.spec.ts
  src/accept-tc/guards/acceptTermsAndCondition.guard.spec.ts
  src/accept-tc/guards/acceptTermsAndCondition.guard.ts
  src/app/components/privacy-policy/privacy-policy.component.spec.ts
  src/app/components/service-down/service-down.component.spec.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/users/containers/edit-user-permissions/edit-user-permission.component.spec.ts
  src/users/containers/invite-user/invite-user.component.spec.ts
  src/users/containers/utils/user-roles-util.spec.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-925

#782 moved beta banner and changed styling
  src/app/containers/header/header.component.html
  src/app/containers/header/header.component.scss
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-782

#991 EUI-7931 Yarn V3 upgrade
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  Dockerfile
  api/.yarn/install-state.gz
  api/webpack-node.config.js
  api/yarn.lock
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-991

#995 EUI-8004 CAA Case selections for assigned and unassigned cases appear on both tabs
  src/caa-cases/caa-cases.routing.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.ts
  src/caa-cases/containers/case-share-complete/case-share-complete.component.spec.ts
  src/caa-cases/containers/case-share-complete/case-share-complete.component.ts
  src/caa-cases/containers/case-share-confirm/case-share-confirm.component.spec.ts
  src/caa-cases/containers/case-share-confirm/case-share-confirm.component.ts
  src/caa-cases/containers/case-share/case-share.component.ts
  src/caa-cases/store/actions/index.ts
  src/caa-cases/store/actions/share-case.action.spec.ts
  src/caa-cases/store/actions/share-case.action.ts
  src/caa-cases/store/effects/share-case.effects.spec.ts
  src/caa-cases/store/effects/share-case.effects.ts
  src/caa-cases/store/reducers/share-case.reducer.spec.ts
  src/caa-cases/store/reducers/share-case.reducer.ts
  src/caa-cases/store/selectors/share-case.selector.ts
  src/caa-cases/store/selectors/share-case.selectors.spec.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-995
