Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2023-12, with the labels that each got.

#1209 EUI-9032: Check Your Answers page amendment
  src/register-org/components/check-your-answers/check-your-answers.component.html
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1209

#1216 enable all tests and fix broken setup
  angular.json
  src/caa-cases/containers/caa-cases/caa-cases.component.spec.ts
  src/organisation/components/pba-number-input/pba-number-input.component.spec.ts
  src/organisation/containers/update-pba-check/update-pba-numbers-check.component.spec.ts
  src/users/containers/user-details/user-details.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1216

#1203 Release 32.1 - Register Other Org
  api/models/registrationData.ts
  api/organisation/index.ts
  api/registerOrganisation/index.ts
  package.json
  src/models/organisation.model.ts
  src/organisation/containers/organisation/organisation.component.html
  src/organisation/containers/organisation/organisation.component.spec.ts
  src/organisation/containers/organisation/organisation.component.ts
  src/organisation/services/organisation.service.ts
  src/organisation/store/effects/organisation.effects.spec.ts
  src/organisation/store/effects/organisation.effects.ts
  src/organisation/utils/index.spec.ts
  src/organisation/utils/index.ts
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  test_codecept/e2e/features/app/registerOtherOrgNavigation.feature
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1203

#1215 GA-31 Update the organisation model to include the profileids property ng 15
  package.json
  src/app/app.module.ts
  src/app/app.routes.ts
  src/models/organisation.model.ts
  src/organisation/components/pba-numbers-form/pba-numbers-form.component.spec.ts
  src/organisation/containers/update-pba-check/update-pba-numbers-check.component.spec.ts
  src/organisation/containers/update-pba-numbers/update-pba-numbers.component.spec.ts
  src/organisation/organisation.routing.ts
  src/organisation/store/actions/organisation.actions.spec.ts
  src/organisation/store/actions/organisation.actions.ts
  src/organisation/store/effects/organisation.effects.spec.ts
  src/organisation/store/reducers/organisation.reducer.ts
  src/users/containers/users/users.component.ts
  src/users/models/prd-users.model.ts
  src/users/services/users.service.ts
  src/users/store/actions/user.actions.spec.ts
  src/users/store/actions/user.actions.ts
  src/users/store/effects/users.effects.spec.ts
  src/users/store/effects/users.effects.ts
  src/users/store/reducers/users.reducer.spec.ts
  test_codecept/e2e/features/pageObjects/inviteUserPage.js
  test_codecept/e2e/features/step_definitions/inviteUser.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1215

#1219 Revert "Release 32.1 - Register Other Org"
  api/models/registrationData.ts
  api/organisation/index.ts
  api/registerOrganisation/index.ts
  package.json
  src/models/organisation.model.ts
  src/organisation/containers/organisation/organisation.component.html
  src/organisation/containers/organisation/organisation.component.spec.ts
  src/organisation/containers/organisation/organisation.component.ts
  src/organisation/services/organisation.service.ts
  src/organisation/store/effects/organisation.effects.spec.ts
  src/organisation/store/effects/organisation.effects.ts
  src/organisation/utils/index.spec.ts
  src/organisation/utils/index.ts
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  test_codecept/e2e/features/app/registerOtherOrgNavigation.feature
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1219

#1218 GA-88 subscribe to the ogd-invite-user-flow feature toggle
  src/app/app-initializer.ts
  src/app/app.constants.ts
  src/app/store/selectors/app.selectors.ts
  src/users/containers/manage-user/manage-user.component.spec.ts
  src/users/containers/manage-user/manage-user.component.ts
  src/users/containers/user-details/user-details.component.ts
  src/users/store/selectors/user.selectors.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1218

#1221 GA-89 create ogd user invite flow guard
  src/users/guards/feature-toggle-ogd-invite-user-flow.guard.ts
  src/users/users.routing.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1221
