Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2023-07, with the labels that each got.

#1022 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1022

#1023 EXUI-402-change in text
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1023

#1029 update advisory suppressions and temp suppress failing test
  test/e2e/features/app/smoke.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1029

#1032 exclude irrelevant content from Fortify scans
  test/java/config/fortify-client.properties
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1032

#1040 Temp disable flaky test scenarios and assertions
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/editPermissions.feature
  test/e2e/features/app/viewOrganisation.feature
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1040
