Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2023-04, with the labels that each got.

#1000 EXUI-208 Migrate .internal url
  api/lib/config/environments/preview.config.ts
  src/shared/services/headers.service.ts
  whitelist.sh
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1000

#1002 EUI-8281 Share case button enabled by default
  src/caa-cases/containers/caa-cases/caa-cases.component.html
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1002

#1003 bug/EUI-8282 common-lib version change to master
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1003
