Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2023-08, with the labels that each got.

#1046 update known issue suppressions
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1046

#1048 EUI-8662 Register other org DX number function
  src/caa-cases/components/caa-filter/caa-filter.component.ts
  src/caa-cases/containers/caa-cases/caa-cases.component.ts
  src/caa-cases/models/caa-cases.model.ts
  src/register-org/components/before-you-start/before-you-start.component.html
  src/register-org/components/before-you-start/before-you-start.component.spec.ts
  src/register-org/components/before-you-start/before-you-start.component.ts
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/company-house-details/company-house-details.component.scss
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.html
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.ts
  src/register-org/components/index.ts
  src/register-org/components/office-addresses/office-addresses.component.html
  src/register-org/components/office-addresses/office-addresses.component.spec.ts
  src/register-org/components/office-addresses/office-addresses.component.ts
  src/register-org/containers/register/register-org.component.ts
  src/register-org/models/registrationdata.model.ts
  src/register-org/register-org.module.ts
  src/register-org/register-org.routing.ts
  src/register-org/services/register-org.service.ts
  src/register/components/index.ts
  src/shared/models/error-message.model.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1048

#1052 use idam api for idam check
  api/idamCheck.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1052

#1053 EUI-8719 Register other org - Contact details
  src/register-org/components/contact-details/contact-details.component.html
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/contact-details/contact-details.component.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/index.ts
  src/register-org/models/contact-details.model.ts
  src/register-org/models/index.ts
  src/register-org/models/registrationdata.model.ts
  src/register-org/register-org.routing.ts
  src/register-org/services/register-org.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1053

#1045 EUI-8697 Register other org organisation type
  api/configuration/references.ts
  api/configuration/ui.ts
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/ithc.config.ts
  api/lib/config/environments/local.config.ts
  api/lib/config/environments/preview.config.ts
  api/lib/config/environments/prod.config.ts
  api/openRoutes.ts
  api/prd/lov/index.ts
  api/prd/lov/models/lovRefData.model.ts
  config/custom-environment-variables.json
  config/default.json
  src/register-org/__mocks__/index.ts
  src/register-org/__mocks__/organisation-types.mock.ts
  src/register-org/__mocks__/other-organisation-types.mock.ts
  src/register-org/components/index.ts
  src/register-org/components/organisation-type/organisation-type.component.html
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/organisation-type/organisation-type.component.ts
  src/register-org/register-org.routing.ts
  src/register/components/index.ts
  src/shared/models/lovRefData.model.ts
  src/shared/services/lov-ref-data.service.spec.ts
  src/shared/services/lov-ref-data.service.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1045

#1047 Feature togggle guard
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/containers/app/app.component.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1047

#1050 EUI-8717 Register other org - Which services will your organisation need to access
  src/register-org/__mocks__/index.ts
  src/register-org/__mocks__/services.mock.ts
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/index.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.spec.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/registered-with-regulator/registered-with-regulator.component.spec.ts
  src/register-org/models/registrationdata.model.ts
  src/register-org/register-org.routing.ts
  src/register-org/services/register-org.service.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1050

#1056 Check your answers
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/index.ts
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/registered-with-regulator/registered-with-regulator.component.spec.ts
  src/register-org/models/registrationdata.model.ts
  src/register-org/register-org.routing.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1056

#1057 EUI-8727 Register other org - New terms and conditions
  src/app/app-initializer.ts
  src/app/app.routes.ts
  src/app/components/index.ts
  src/app/components/terms-and-conditions-register-other-org/terms-and-conditions-register-other-org.component.html
  src/app/components/terms-and-conditions-register-other-org/terms-and-conditions-register-other-org.component.ts
  src/app/components/terms-and-conditions-register-other-org/terms-and-conditions-register-other-org.spec.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.spec.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.ts
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/index.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1057

#1059 Update suppressions causing nightly build failures
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1059

#1067 EUI-8762 Register other org - Amend DX reference page
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.html
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1067

#1066 EUI-8752 Register other org - Before you start page functionality
  src/register-org/components/before-you-start/before-you-start.component.html
  src/register-org/components/before-you-start/before-you-start.component.spec.ts
  src/register-org/components/before-you-start/before-you-start.component.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1066

#1065 Feature/e UI 8694 address buttons
  api/addresses/index.ts
  api/application.ts
  api/auth/index.ts
  api/configuration/references.ts
  api/configuration/ui.ts
  api/lib/proxy.ts
  api/openRoutes.ts
  api/routes.ts
  api/server.ts
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/components/get-help/get-help.component.spec.ts
  src/organisation/components/pba-number-input/pba-number-input.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/company-house-details/company-house-details.component.ts
  src/register-org/constants/register-org-constants.ts
  src/register-org/containers/index.ts
  src/register-org/containers/registered-address/registered-address.component.html
  src/register-org/containers/registered-address/registered-address.component.spec.ts
  src/register-org/containers/registered-address/registered-address.component.ts
  src/register-org/register-org.module.ts
  src/register-org/register-org.routing.ts
  src/register/register.module.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1065

#1063 EUI-8733 Register Other Org - What PBA numbers does your organisation use
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.html
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.spec.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1063

#1060 Template changes
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.spec.ts
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.ts
  src/register-org/models/index.ts
  src/register-org/models/regulatory-organisation.enum.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1060
