Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2023-10, with the labels that each got.

#1122 Post Registration Data
  api/models/registrationData.ts
  api/openRoutes.ts
  api/registerOrganisation/index.ts
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/check-your-answers/regulator-list/regulator-list.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
  src/register-org/components/registration-submitted/registration-submitted.component.spec.ts
  src/register-org/components/registration-submitted/registration-submitted.component.ts
  src/register-org/services/register-org.service.spec.ts
  src/register-org/services/register-org.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1122

#1124 EUI-8835 Register Other Org - Organisation page changes
  src/models/organisation.model.ts
  src/organisation/containers/organisation/organisation.component.html
  src/organisation/containers/organisation/organisation.component.spec.ts
  src/organisation/containers/organisation/organisation.component.ts
  src/organisation/utils/index.spec.ts
  src/organisation/utils/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1124

#1128 e2e test for register other create scenario
  package.json
  test_codecept/e2e/features/app/registerOtherOrg.feature
  test_codecept/e2e/features/pageObjects/registerOtherOrg/beforeYouStartPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/checkYourAnswersPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/companyHouseDetailsPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/contactDetailsPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/documentExchangeReferenceDetailsPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/documentExchangeReferencePage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/individualRegisteredWithRegulatorDetailsPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/individualRegisteredWithRegulatorPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/organisationServicesAccessPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/organisationTypePage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/paymentByAccountDetailsPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/paymentByAccountPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/registeredAddressManualPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/registeredAddressPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/regulatoryOrganisationTypePage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/workflow.js
  test_codecept/e2e/features/step_definitions/registerOtherOrg.steps.js
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1128

#1131 Add required changes and test changes
  package.json
  src/register-org/components/company-house-details/company-house-details.component.ts
  src/register-org/components/contact-details/contact-details.component.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/components/organisation-type/organisation-type.component.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.ts
  src/register-org/components/payment-by-account/payment-by-account.component.ts
  src/register-org/containers/registered-address/registered-address.component.spec.ts
  src/register-org/containers/registered-address/registered-address.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1131

#1117 Feature/EUI 8729
  api/auth/index.ts
  charts/xui-mo-webapp/values.preview.template.yaml
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/organisation-type/organisation-type.component.html
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/organisation-type/organisation-type.component.ts
  src/register-org/models/registration-data.model.ts
  test_codecept/e2e/features/app/registerOtherOrg.feature
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1117

#1134 EXUI-803: Use ccpay-web-component's
  package.json
  src/register-org/containers/registered-address/registered-address.component.html
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1134

#1133 yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1133

#1137 EMUI-803: chart 2.4.18 is deprecated, upgraded to at least 3.0.0
  .nvmrc
  .nvrmc
  charts/xui-mo-webapp/Chart.yaml
  package.json
  test_codecept/integration/tests/test.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1137

#1138 more logging
  api/.yarn/install-state.gz
  package.json
  test_codecept/codeceptCommon/hooks.js
  test_codecept/e2e/features/step_definitions/loginLogout.steps.js
  test_codecept/integration/tests/utils/getCookie.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1138

#1135 Feature/e UI 8869
  api/models/registrationData.ts
  api/registerOrganisation/index.ts
  src/organisation/containers/organisation/organisation.component.html
  src/organisation/containers/organisation/organisation.component.spec.ts
  src/organisation/containers/organisation/organisation.component.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1135

#1136 Update app.routes.ts
  package.json
  src/app/app.routes.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1136

#1142 fix Address optional fields
  api/models/registrationData.ts
  api/registerOrganisation/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1142

#1132 EUI-8841 Register Other Org - Accessibility issues
  package.json
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/index.html
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.html
  src/register-org/components/regulator-details/regulator-details.component.html
  src/shared/modules/loader/components/loader.component.html
  test_codecept/accessibility/tests/registerOrgAndOtherOrgs.js
  test_codecept/backendMock/app.js
  test_codecept/backendMock/services/rdCommondata/index.js
  test_codecept/backendMock/services/rdCommondata/routes.js
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/codeceptCommon/customHelper.js
  test_codecept/codeceptCommon/elements.js
  test_codecept/codeceptCommon/hooks.js
  test_codecept/e2e/features/app/createOrganisation.feature
  test_codecept/e2e/features/app/loginLogout.feature
  test_codecept/e2e/features/app/registerOtherOrg.feature
  test_codecept/e2e/features/app/registerOtherOrgNavigation.feature
  test_codecept/e2e/features/app/registerOtherOrgPageValidations.feature
  test_codecept/e2e/features/pageObjects/registerOtherOrg/companyHouseDetailsPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/registeredAddressPage.js
  test_codecept/e2e/features/pageObjects/registerOtherOrg/workflow.js
  test_codecept/e2e/features/step_definitions/createOrganisation.steps.js
  test_codecept/e2e/features/step_definitions/inviteUser.steps.js
  test_codecept/e2e/features/step_definitions/registerOrgWorkflow.steps.js
  test_codecept/e2e/features/step_definitions/registerOtherOrg.steps.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1132

#1143 Override the LD Key for Preview
  api/configuration/references.ts
  api/configurationUI/index.ts
  charts/xui-mo-webapp/values.preview.template.yaml
  config/custom-environment-variables.json
  config/default.json
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1143

#1147 EUI-8921 Register Other Org - Back link issues
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.spec.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.ts
  test_codecept/codeceptCommon/codecept.conf.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1147

#1148 EUI-8929 Register Other Org - Individual regulator corrections
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1148

#1149 Feature/e UI 8831 review roo
  package.json
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/containers/redirect/redirect.component.spec.ts
  src/caa-cases/store/reducers/share-case.reducer.spec.ts
  src/organisation/components/pba-success-summary/pba-success-summary.component.spec.ts
  src/register-org/components/before-you-start/before-you-start.component.html
  src/register-org/components/before-you-start/before-you-start.component.spec.ts
  src/register-org/components/before-you-start/before-you-start.component.ts
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-type/organisation-type.component.html
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/payment-by-account/payment-by-account.component.html
  src/register-org/components/regulator-details/regulator-details.component.html
  src/register-org/containers/registered-address/registered-address.component.html
  src/users/containers/user-details/user-details.component.spec.ts
  src/users/store/reducers/users.reducer.spec.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1149

#1160 Update Chart.yaml
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1160

#1155 Fix issue
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/organisation-type/organisation-type.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1155

#1153 EUI-8928 Register Other Org - CYA page corrections
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1153

#1161 Make error message changes
  package.json
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.ts
  src/register-org/components/regulator-details/regulator-details.component.html
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1161

#1157 EUI-8927 Register Other Org - PBA details page fixes
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.html
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.spec.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.ts
  src/register-org/models/error-messages.model.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1157

#1166 Bug/EUI 8945
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/check-your-answers/regulator-list/regulator-list.component.html
  src/register-org/components/check-your-answers/regulator-list/regulator-list.component.spec.ts
  src/register-org/components/check-your-answers/regulator-list/regulator-list.component.ts
  src/register-org/components/regulator-details/regulator-details.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1166

#1164 EUI-8926 Register Other Org - Organisation regulators fixes
  src/register-org/components/regulator-details/regulator-details.component.html
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1164

#1167 Make address postcode fix
  src/register-org/containers/registered-address/registered-address.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1167

#1163 Make changes to error message display on 400
  api/registerOrganisation/index.ts
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/organisation-type/organisation-type.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1163

#1168 yarn audit for pipeline fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1168
