Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2023-09, with the labels that each got.

#1070 Add registration submitted page
  src/register-org/components/index.ts
  src/register-org/components/registration-submitted/registration-submitted.component.html
  src/register-org/components/registration-submitted/registration-submitted.component.spec.ts
  src/register-org/components/registration-submitted/registration-submitted.component.ts
  src/register-org/register-org.routing.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1070

#1068 EUI-8715/EUI-8751: Register Other Org - regulatory organisation page functionality and "Remove" button (display only)
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/registered-with-regulator/registered-with-regulator.component.spec.ts
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.spec.ts
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.ts
  src/register-org/models/index.ts
  src/register-org/models/registrationdata.model.ts
  src/register-org/models/regulator.model.ts
  src/register-org/models/regulatory-organisation-type.model.ts
  src/register-org/models/regulatory-organisation.enum.ts
  src/register-org/services/register-org.service.ts
  src/shared/models/lovRefData.model.ts
  src/shared/services/lov-ref-data.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1068

#1073 Feature/e UI 8750 navigation register other org
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/contact-details/contact-details.component.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/index.ts
  src/register-org/components/office-addresses/office-addresses.component.html
  src/register-org/components/office-addresses/office-addresses.component.spec.ts
  src/register-org/components/office-addresses/office-addresses.component.ts
  src/register-org/components/organisation-type/organisation-type.component.html
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/organisation-type/organisation-type.component.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.ts
  src/register-org/components/registered-regulator/registered-regulator.component.html
  src/register-org/components/registered-regulator/registered-regulator.component.ts
  src/register-org/components/registered-with-regulator/registered-with-regulator.component.ts
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
  src/register-org/containers/registered-address/registered-address.component.html
  src/register-org/containers/registered-address/registered-address.component.ts
  src/register-org/models/organisation-type.enum.ts
  src/register-org/models/registrationdata.model.ts
  src/register-org/register-org.module.ts
  src/register-org/register-org.routing.ts
  src/register-org/services/register-org.service.ts
  src/shared/models/error-message.model.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1073

#1078 Feature/8704 31.1 changes
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1078

#1077 Bug/e UI 8800
  src/register-org/register-org.routing.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1077, enable_keep_helm

#1074 EUI-8781 Register other org - Regulator display amendment
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.spec.ts
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.ts
  src/register-org/services/register-org.service.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1074, enable_keep_helm

#1072 Feature/EUI 8755
  Jenkinsfile_CNP
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  src/register-org/models/error-messages.model.ts
  src/register-org/models/index.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1072, enable_keep_helm

#1086 audit changes
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1086

#1087 Update values.yaml
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.yaml
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1087

#1088 EUI-8784 Register other org - PBA number yes no functionality
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/payment-by-account/payment-by-account.component.html
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/payment-by-account/payment-by-account.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1088

#1080 Feature/EUI 8776
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.spec.ts
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.ts
  src/register-org/models/regulatory-organisation.enum.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1080

#1090 Feature/EUI 8796
  src/app/components/terms-and-conditions-register-other-org/terms-and-conditions-register-other-org.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1090

#1079 EUI-8728 Register Other Org - Personal regulator
  api/auth/index.ts
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/index.ts
  src/register-org/components/individual-registered-with-regulator-details/individual-registered-with-regulator-details.component.html
  src/register-org/components/individual-registered-with-regulator-details/individual-registered-with-regulator-details.component.spec.ts
  src/register-org/components/individual-registered-with-regulator-details/individual-registered-with-regulator-details.component.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.html
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.ts
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.html
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.ts
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.spec.ts
  src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.ts
  src/register-org/containers/index.ts
  src/register-org/models/index.ts
  src/register-org/models/registrationdata.model.ts
  src/register-org/models/regulator-type.enum.ts
  src/register-org/register-org.routing.ts
  src/register-org/services/register-org.service.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1079

#1062 EXUI-705: Automated Suppression Updates
  .github/workflows/dependency-check.yml
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1062

#1083 Bug/ex UI 779 mo nightly pipeline fix
  .nvmrc
  Jenkinsfile_nightly
  package.json
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1083

#1089 EUI-8768 Register other org - Cancel link functionality
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  src/register-org/components/contact-details/contact-details.component.html
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/contact-details/contact-details.component.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.html
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.html
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.ts
  src/register-org/components/office-addresses/office-addresses.component.html
  src/register-org/components/office-addresses/office-addresses.component.spec.ts
  src/register-org/components/office-addresses/office-addresses.component.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.spec.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/components/organisation-type/organisation-type.component.html
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/organisation-type/organisation-type.component.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.html
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.spec.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.ts
  src/register-org/components/payment-by-account/payment-by-account.component.html
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/payment-by-account/payment-by-account.component.ts
  src/register-org/components/registered-regulator/registered-regulator.component.html
  src/register-org/components/registered-regulator/registered-regulator.component.ts
  src/register-org/components/regulator-details/regulator-details.component.html
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.ts
  src/register-org/containers/register/register-org.component.spec.ts
  src/register-org/containers/register/register-org.component.ts
  src/register-org/containers/registered-address/registered-address.component.html
  src/register-org/containers/registered-address/registered-address.component.spec.ts
  src/register-org/containers/registered-address/registered-address.component.ts
  src/register-org/services/register-org.service.spec.ts
  src/register-org/services/register-org.service.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1089

#1097 EUI-8811 Register Other Org - Individual regulator yes no functionality
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.html
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1097

#1096 EUI-8801 Register Other Org - Contact details functionality
  src/register-org/components/contact-details/contact-details.component.html
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/contact-details/contact-details.component.ts
  src/register-org/models/contact-details.enum.ts
  src/register-org/models/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1096

#1095 Add validation
  src/register-org/components/index.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.spec.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/components/service-down/service-down.component.html
  src/register-org/components/service-down/service-down.component.spec.ts
  src/register-org/components/service-down/service-down.component.ts
  src/register-org/models/error-messages.model.ts
  src/register-org/register-org.routing.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1095

#1101 Bug/ex UI 855 mo nightly pipeline fix
  Jenkinsfile_nightly
  api/caaCases/caaCases.util.ts
  api/caaCases/index.ts
  test/integration/tests/post_Invite_User.ts
  test/integration/tests/post_ReInvite_User.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1101

#1103 register other org workflow pages a11y tests added
  test_codecept/accessibility/tests/registerOrgAndOtherOrgs.js
  test_codecept/e2e/features/app/registerOrgOtherOrg.feature
  test_codecept/e2e/features/pageObjects/registerOrgWorkFlow.js
  test_codecept/e2e/features/step_definitions/registerOrgWorkflow.steps.js
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1103

#1104 Revert "Bug/ex UI 855 mo nightly pipeline fix"
  Jenkinsfile_nightly
  api/caaCases/caaCases.util.ts
  api/caaCases/index.ts
  test/integration/tests/post_Invite_User.ts
  test/integration/tests/post_ReInvite_User.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1104

#1099 Add non-postcode validation and persistence
  package.json
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/containers/registered-address/registered-address.component.html
  src/register-org/containers/registered-address/registered-address.component.spec.ts
  src/register-org/containers/registered-address/registered-address.component.ts
  src/register-org/models/registrationdata.model.ts
  src/register-org/register-org.routing.ts
  src/register-org/services/register-org.service.spec.ts
  src/register-org/services/register-org.service.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1099

#1100 Add validation
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.html
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.ts
  src/register-org/components/regulator-details/regulator-details.component.ts
  src/register-org/models/error-messages.model.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1100

#1108 jenkins fix
  .github/renovate.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1108

#1107 Feature/EUI 8730
  api/organisationTypesRouter/mockOrganisationTypes.ts
  src/register-org/components/regulator-details/regulator-details.component.html
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/models/regulatory-organisation.enum.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1107

#1105 Feature/EUI 8786
  package.json
  src/custom-validators/postcode.validator.spec.ts
  src/custom-validators/postcode.validator.ts
  src/register-org/containers/registered-address/registered-address.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1105

#1106 EUI-8821 EUI-8731 Register Other Org - Organisation services amendments
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.spec.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/constants/register-org-constants.ts
  src/register-org/models/error-messages.model.ts
  src/register-org/models/index.ts
  src/register-org/models/organisation-service.model.ts
  src/register-org/models/registration-data.model.ts
  src/register-org/services/register-org.service.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1106

#1093 Validation for the PBA numbers
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.html
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.ts
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/models/registration-data.model.ts
  src/register-org/services/register-org.service.spec.ts
  src/register-org/services/register-org.service.ts
  src/shared/shared.module.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1093

#1123 disabled fortifyscan from jenkins
  Jenkinsfile_nightly
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1123

#1113 EUI-8838 Register Other Org - Back link not working
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  src/register-org/components/contact-details/contact-details.component.spec.ts
  src/register-org/components/contact-details/contact-details.component.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.spec.ts
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.ts
  src/register-org/components/index.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.ts
  src/register-org/components/office-addresses/office-addresses.component.html
  src/register-org/components/office-addresses/office-addresses.component.spec.ts
  src/register-org/components/office-addresses/office-addresses.component.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.spec.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/organisation-type/organisation-type.component.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.spec.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.ts
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/payment-by-account/payment-by-account.component.ts
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.ts
  src/register-org/containers/register/register-org.component.spec.ts
  src/register-org/containers/register/register-org.component.ts
  src/register-org/containers/registered-address/registered-address.component.html
  src/register-org/containers/registered-address/registered-address.component.spec.ts
  src/register-org/containers/registered-address/registered-address.component.ts
  src/register-org/register-org.routing.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1113

#1112 Feature/e UI 8771 postcode lookup validation
  package.json
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.ts
  src/register-org/containers/registered-address/registered-address.component.html
  src/register-org/containers/registered-address/registered-address.component.spec.ts
  src/register-org/containers/registered-address/registered-address.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1112
