Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2023-11, with the labels that each got.

#1176 Upgrade to node version 15
  .nvmrc
  .yarn/releases/yarn-3.5.0.cjs
  .yarn/releases/yarn-3.6.3.cjs
  .yarnrc.yml
  angular.json
  package.json
  test_codecept/e2e/features/app/registerOtherOrgNavigation.feature
  test_codecept/e2e/features/app/registerOtherOrgPageValidations.feature
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1176

#1178 ROO test updates to use user targetting
  test_codecept/e2e/features/app/createOrganisation.feature
  test_codecept/e2e/features/app/inviteUser.feature
  test_codecept/e2e/features/app/registerOtherOrg.feature
  test_codecept/e2e/features/app/registerOtherOrgNavigation.feature
  test_codecept/e2e/features/app/registerOtherOrgPageValidations.feature
  test_codecept/e2e/features/step_definitions/loginLogout.steps.js
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1178

#1158 Make changes to post services correctly
  api/models/registrationData.ts
  api/registerOrganisation/index.ts
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.spec.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/models/registration-data.model.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1158

#1169 Add common-lib tag
  package.json
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/contact-details/contact-details.component.html
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.html
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-type/organisation-type.component.html
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.html
  src/register-org/components/payment-by-account/payment-by-account.component.html
  src/register-org/components/regulator-details/regulator-details.component.html
  src/register-org/containers/registered-address/registered-address.component.html
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1169

#1181 EUI-8961 ROO Companies house page corrections
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  src/register-org/components/organisation-type/organisation-type.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1181

#1183 EUI-8969: MyHMCTS Terms and Conditions changes
  src/app/components/terms-and-conditions-register-other-org/terms-and-conditions-register-other-org.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/organisation-type/organisation-type.component.html
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1183

#1174 Use error message, not description
  api/registerOrganisation/index.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1174

#1180 Update register-org.component.ts
  src/register-org/containers/register/register-org.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1180

#1179 Bug/e UI 8963 address inline errors
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1179

#1185 EUI-8974 ROO Regulator page corrections
  src/register-org/components/regulator-details/regulator-details.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1185

#1187 yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1187

#1186 EUI-8971/EUI-8972: Regulator Details amendments
  src/register-org/components/regulator-details/regulator-details.component.html
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.ts
  src/register-org/models/regulatory-organisation.enum.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1186

#1144 Feature/register other org sprint 31.5 EXUI_MO_3.0.63
  api/registerOrganisation/index.ts
  package.json
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.ts
  src/app/containers/redirect/redirect.component.spec.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/caa-cases/store/reducers/share-case.reducer.spec.ts
  src/index.html
  src/organisation/components/pba-success-summary/pba-success-summary.component.spec.ts
  src/register-org/components/before-you-start/before-you-start.component.html
  src/register-org/components/before-you-start/before-you-start.component.spec.ts
  src/register-org/components/before-you-start/before-you-start.component.ts
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/check-your-answers/regulator-list/regulator-list.component.html
  src/register-org/components/check-your-answers/regulator-list/regulator-list.component.spec.ts
  src/register-org/components/check-your-answers/regulator-list/regulator-list.component.ts
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.spec.ts
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.spec.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/components/organisation-type/organisation-type.component.html
  src/register-org/components/organisation-type/organisation-type.component.spec.ts
  src/register-org/components/organisation-type/organisation-type.component.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.html
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.spec.ts
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.ts
  src/register-org/components/payment-by-account/payment-by-account.component.html
  src/register-org/components/payment-by-account/payment-by-account.component.spec.ts
  src/register-org/components/payment-by-account/payment-by-account.component.ts
  src/register-org/components/regulator-details/regulator-details.component.html
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.ts
  src/register-org/containers/registered-address/registered-address.component.html
  src/register-org/containers/registered-address/registered-address.component.ts
  src/register-org/models/error-messages.model.ts
  src/shared/modules/loader/components/loader.component.html
  src/users/containers/user-details/user-details.component.spec.ts
  src/users/store/reducers/users.reducer.spec.ts
  test_codecept/accessibility/tests/registerOrgAndOtherOrgs.js
  test_codecept/backendMock/app.js
  test_codecept/backendMock/services/rdCommondata/index.js
  test_codecept/backendMock/services/rdCommondata/routes.js
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/e2e/features/app/createOrganisation.feature
  test_codecept/e2e/features/app/inviteUser.feature
  test_codecept/e2e/features/app/registerOtherOrg.feature
  test_codecept/e2e/features/app/registerOtherOrgNavigation.feature
  test_codecept/e2e/features/app/registerOtherOrgPageValidations.feature
  test_codecept/e2e/features/app/unassignedCases.feature
  test_codecept/e2e/features/step_definitions/loginLogout.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1144

#1193 ROO test disbale for AAT config issue
  test_codecept/e2e/features/app/registerOtherOrg.feature
  test_codecept/e2e/features/app/registerOtherOrgNavigation.feature
  test_codecept/e2e/features/app/registerOtherOrgPageValidations.feature
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1193

#1037 update PACT Provider
  api/test/pact/pact-tests/feePayApi/getAccounts.spec.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1037

#1027 Add test for getUsers
  api/test/pact/pact-tests/pactFixtures.ts
  api/test/pact/pact-tests/pactUtil.ts
  api/test/pact/pact-tests/rdProfessionalApi/getUsers.spec.ts
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1027

#1190 Feature/EUI 8952
  Jenkinsfile_parameterized
  api/auth/index.ts
  api/configuration/references.ts
  api/configurationUI/index.ts
  api/registerOrganisation/index.ts
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  test_codecept/backendMock/local-mock.json
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1190

#1028 Add pact test
  api/test/pact/pact-tests/pactFixtures.ts
  api/test/pact/pact-tests/pactUtil.ts
  api/test/pact/pact-tests/s2sAuth/postS2SLease.spec.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1028

#1188 EUI-8925 ROO Minor corrections on several pages
  package.json
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/contact-details/contact-details.component.html
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.html
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-type/organisation-type.component.html
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.html
  src/register-org/components/payment-by-account/payment-by-account.component.html
  src/register-org/components/registration-submitted/registration-submitted.component.html
  src/register-org/components/regulator-details/regulator-details.component.html
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1188

#1197 yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1197

#1195 Update values.yaml
  charts/xui-mo-webapp/values.yaml
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1195

#1191 Feature/register other org sprint 31.6 - EXUI_MO_3.0.64
  Jenkinsfile_parameterized
  api/auth/index.ts
  api/configuration/references.ts
  api/configurationUI/index.ts
  api/models/registrationData.ts
  api/registerOrganisation/index.ts
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  package.json
  src/app/components/terms-and-conditions-register-other-org/terms-and-conditions-register-other-org.component.html
  src/register-org/components/before-you-start/before-you-start.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/company-house-details/company-house-details.component.html
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  src/register-org/components/contact-details/contact-details.component.html
  src/register-org/components/document-exchange-reference-details/document-exchange-reference-details.component.html
  src/register-org/components/document-exchange-reference/document-exchange-reference.component.html
  src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.spec.ts
  src/register-org/components/organisation-services-access/organisation-services-access.component.ts
  src/register-org/components/organisation-type/organisation-type.component.html
  src/register-org/components/payment-by-account-details/payment-by-account-details.component.html
  src/register-org/components/payment-by-account/payment-by-account.component.html
  src/register-org/components/registration-submitted/registration-submitted.component.html
  src/register-org/components/regulator-details/regulator-details.component.html
  src/register-org/components/regulator-details/regulator-details.component.spec.ts
  src/register-org/components/regulator-details/regulator-details.component.ts
  src/register-org/containers/register/register-org.component.ts
  src/register-org/containers/registered-address/registered-address.component.html
  src/register-org/models/registration-data.model.ts
  src/register-org/models/regulatory-organisation.enum.ts
  test_codecept/backendMock/local-mock.json
  test_codecept/e2e/features/app/registerOtherOrgPageValidations.feature
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1191

#1201 Bug/e UI 8991 aat address issue
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.yaml
  config/default.json
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1201

#1202 Ex UI 1118 pipeline mo nightly dependency build fixes
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1202

#1182 Add tag
  package.json
  test_codecept/e2e/features/app/registerOtherOrgNavigation.feature
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1182

#1200 Bug/e UI 8965 post registrators
  api/organisation/index.ts
  api/registerOrganisation/index.ts
  src/models/organisation.model.ts
  src/organisation/containers/organisation/organisation.component.html
  src/organisation/containers/organisation/organisation.component.spec.ts
  src/organisation/containers/organisation/organisation.component.ts
  src/organisation/services/organisation.service.ts
  src/organisation/store/effects/organisation.effects.spec.ts
  src/organisation/store/effects/organisation.effects.ts
  src/organisation/utils/index.spec.ts
  src/organisation/utils/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1200

#1204 yarn audit change
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1204

#1206 yarn audit vulnurability check
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1206
