Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2024-03, with the labels that each got.

#1272 GA-183
  api/editUserPermissions/index.ts
  api/inviteUser/index.ts
  api/refresh-user/index.ts
  src/users/components/index.ts
  src/users/components/jurisdictions-access-options/jurisdiction-access-options.component.html
  src/users/components/jurisdictions-access-options/jurisdiction-access-options.component.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.html
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.spec.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.scss
  src/users/components/solicitor-profile-content/solicitor-profile-content.component.html
  src/users/components/standard-user-permissions/standard-user-permissions.component.html
  src/users/components/user-personal-details/user-personal-details.component.html
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1272

#1280 puppeteer upgrade
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1280

#1267 version change for common-lib library- DO_NOT_MERGE
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1267
