Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2024-06, with the labels that each got.

#1286 EXUI-1810 - Angular upgrade
  angular.json
  api/tsconfig.json
  package.json
  src/accept-tc/guards/acceptTermsAndCondition.guard.ts
  src/accept-tc/store/effects/acept-tc.effects.ts
  src/app/app.module.ts
  src/app/components/get-help/get-help.component.html
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/terms-and-conditions-register-other-org/terms-and-conditions-register-other-org.component.html
  src/app/guards/termsCondition.guard.ts
  src/app/store/effects/app.effects.ts
  src/app/store/effects/router.effect.ts
  src/caa-cases/guards/feature-toggle.guard.ts
  src/caa-cases/guards/user-role.guard.ts
  src/fee-accounts/guards/acccounts-summary.guards.ts
  src/fee-accounts/guards/accounts.guard.ts
  src/fee-accounts/guards/feature-toggle-account.guard.ts
  src/fee-accounts/store/effects/fee-accounts.effects.ts
  src/fee-accounts/store/effects/single-fee-account.effects.ts
  src/organisation/guards/organisation.guard.ts
  src/organisation/store/effects/organisation.effects.ts
  src/organisation/store/effects/pba.effects.ts
  src/organisation/store/reducers/organisation.reducer.ts
  src/register/store/effects/registration.effects.ts
  src/shared/guards/health-check.guard.ts
  src/shared/guards/user-role.guard.ts
  src/test.ts
  src/user-profile/guards/auth.guard.ts
  src/user-profile/guards/user.guard.ts
  src/user-profile/store/effects/user-profile.effects.ts
  src/users/guards/feature-toggle-edit-user.guard.ts
  src/users/guards/invite-user-success.guard.ts
  src/users/store/effects/invite-user.effects.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1286

#1291 Exui 1977 add addressline3
  package.json
  src/organisation/containers/organisation/organisation.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1291

#1297 cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1297

#1292 EXUI-2011 - Update ejs to remove critical vuln
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1292

#1293 EXUI-2012: Resolve crypto-js CVE
  package.json
  src/shared/services/cryptoWrapper.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1293
