Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2024-02, with the labels that each got.

#1254 GA-61-B
  src/users/containers/user-details/user-details.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1254

#1208 Accesibility - updated commonlib version
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1208

#1264 GA - User details
  src/users/containers/user-details/user-details.component.ts
  src/users/store/actions/user.actions.ts
  src/users/store/effects/users.effects.spec.ts
  src/users/store/effects/users.effects.ts
  src/users/store/reducers/users.reducer.spec.ts
  src/users/store/reducers/users.reducer.ts
  src/users/store/selectors/user.selectors.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1264

#1268 MO nightly pipeline build fix yarn audit
  test_codecept/codeceptCommon/codecept.conf.ts
  test_codecept/e2e/features/pageObjects/inviteUserPage.js
  test_codecept/integration/tests/get_Organisation_User_Details.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1268

#1262 package.json update - gov-frontend 4.7.0
  .gitignore
  package.json
  src/app/containers/app/app.component.spec.ts
  test_codecept/e2e/features/app/inviteUser.feature
  test_codecept/e2e/features/app/loginLogout.feature
  test_codecept/e2e/features/app/viewUser.feature
  test_codecept/e2e/features/pageObjects/inviteUserPage.js
  test_codecept/ngIntegration/tests/stepDefinitions/nodeMock.steps.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1262

#1234 GA-127 accordion style update post govuk lib v4
  src/users/components/solicitor-profile-content/solicitor-profile-content.component.scss
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1234

#1269 EXUI-909 Use standard redis SKU on non-prod environments
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: Do not merge, ns:xui, prd:xui, destroy, rel:xui-mo-webapp-pr-1269

#1255 GA-44 - Bugs
  src/users/components/search-filter-users/search-filter-users.component.spec.ts
  src/users/components/search-filter-users/search-filter-users.component.ts
  test_codecept/e2e/features/app/editPermissions.feature
  test_codecept/e2e/features/pageObjects/inviteUserPage.js
  test_codecept/e2e/features/step_definitions/inviteUser.steps.js
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1255
