Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2024-10, with the labels that each got.

#1309 exui-2406-addition of text
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/containers/registered-address/registered-address.component.html
  test_codecept/integration/tests/get_Organisation_User_Details.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1309

#1304 remove deprecated defineSupportCode
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  test/e2e/config/common.conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/viewOrganisation.feature
  test/e2e/features/pageObjects/loginLogoutObjects.js
  test/e2e/features/step_definitions/acceptTermsAndConditions.steps.js
  test/e2e/features/step_definitions/approveOrg.steps.js
  test/e2e/features/step_definitions/createOrganisation.steps.js
  test/e2e/features/step_definitions/dataSetUp.steps.js
  test/e2e/features/step_definitions/headerPage.steps.js
  test/e2e/features/step_definitions/inviteUser.steps.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/e2e/features/step_definitions/viewOrganisation.steps.js
  test/e2e/features/step_definitions/viewUser.steps.js
  test/e2e/support/hooks.js
  test/e2e/support/timeout.js
  test/e2e/support/world.js
  test_codecept/e2e/features/step_definitions/acceptTermsAndConditions.steps.js
  test_codecept/e2e/features/step_definitions/approveOrg.steps.js
  test_codecept/e2e/features/step_definitions/createOrganisation.steps.js
  test_codecept/e2e/features/step_definitions/dataSetUp.steps.js
  test_codecept/e2e/features/step_definitions/inviteUser.steps.js
  test_codecept/e2e/features/step_definitions/viewOrganisation.steps.js
  test_codecept/e2e/features/step_definitions/viewUser.steps.js
  test_codecept/e2e/support/hooks.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1304

#1311 EXUI-2411 - Update ejs version
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1311

#1305 dummy test
  Jenkinsfile_CNP
  package.json
  test_codecept/accessibility/tests/organisationTab.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1305
