Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2024-07, with the labels that each got.

#1288 EXUI-332 - Exclude config info from bundle
  package.json
  src/app/app.module.ts
  src/environments/environment.prod.ts
  src/shared/services/headers.service.ts
  src/shared/services/logger.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1288

#1283 EXUI-1301 - error message updated
  api/configurationUI/index.ts
  api/registerOrganisation/index.ts
  package.json
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1283

#1287 exui-1427-pa11y-test-failure
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/organisation-services-access/organisation-services-access.component.html
  src/users/components/invite-user-form/invite-user-form.component.html
  src/users/store/reducers/invite-user.reducer.ts
  test_codecept/accessibility/helpers/pa11yUtil.js
  test_codecept/accessibility/reporter/reportsMerger.js
  test_codecept/accessibility/tests/UnassignedCases.js
  test_codecept/accessibility/tests/registerOrgAndOtherOrgs.js
  test_codecept/accessibility/tests/unauthenticatedUrls.js
  test_codecept/accessibility/tests/usersTab.js
  test_codecept/backendMock/local-mock.json
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1287

#1300 EXUI-375: Use v2.29.0 node-lib
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1300

#1289 EXUI-929 - Update LD Client
  charts/xui-mo-webapp/values.preview.template.yaml
  package.json
  src/app/containers/app/app.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1289

#1298 exui-667-upgrade-node-18
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1298
