Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2024-01, with the labels that each got.

#1226 DTSPO-15909 - migrated Application Insights
  infrastructure/main.tf
  infrastructure/output.tf
Labels: ns:xui, prd:xui, add-or-update, rel:xui-mo-webapp-pr-1226

#1225 GA-74 Standard User Permissions for OGD flow
  src/users/components/index.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.html
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.spec.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.ts
  src/users/components/standard-user-permissions/standard-user-permissions.component.html
  src/users/components/standard-user-permissions/standard-user-permissions.component.spec.ts
  src/users/components/standard-user-permissions/standard-user-permissions.component.ts
  src/users/containers/manage-user/manage-user.component.html
  src/users/containers/manage-user/manage-user.component.ts
  src/users/users.module.ts
Labels: ns:xui, prd:xui, destroy, rel:xui-mo-webapp-pr-1225

#1223 GA-75 manage user additional access checkboxes from organisation
  src/organisation/store/reducers/organisation.reducer.ts
  src/users/components/index.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.html
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.spec.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.ts
  src/users/components/standard-user-permissions/standard-user-permissions.component.html
  src/users/components/standard-user-permissions/standard-user-permissions.component.spec.ts
  src/users/components/standard-user-permissions/standard-user-permissions.component.ts
  src/users/containers/manage-user/manage-user.component.html
  src/users/containers/manage-user/manage-user.component.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1223

#1227 Added 6 new components for static content for each of the OGD profiles
  src/users/containers/index.ts
  src/users/containers/ogd-cafcass-cy-profile-content/ogd-cafcass-cy-profile-content.component.html
  src/users/containers/ogd-cafcass-cy-profile-content/ogd-cafcass-cy-profile-content.component.ts
  src/users/containers/ogd-cafcass-en-profile-content/ogd-cafcass-en-profile-content.component.html
  src/users/containers/ogd-cafcass-en-profile-content/ogd-cafcass-en-profile-content.component.ts
  src/users/containers/ogd-cica-profile-content/ogd-cica-profile-content.component.html
  src/users/containers/ogd-cica-profile-content/ogd-cica-profile-content.component.ts
  src/users/containers/ogd-dwp-profile-content/ogd-dwp-profile-content.component.html
  src/users/containers/ogd-dwp-profile-content/ogd-dwp-profile-content.component.ts
  src/users/containers/ogd-hmrc-profile-content/ogd-hmrc-profile-content.component.html
  src/users/containers/ogd-hmrc-profile-content/ogd-hmrc-profile-content.component.ts
  src/users/containers/ogd-ho-profile-content/ogd-ho-profile-content.component.html
  src/users/containers/ogd-ho-profile-content/ogd-ho-profile-content.component.ts
  src/users/users.module.ts
Labels: ns:xui, prd:xui, destroy, rel:xui-mo-webapp-pr-1227

#1217 GA-44 - Enable user search by name/email
  src/users/components/index.ts
  src/users/components/search-filter-users/search-filter-users.component.html
  src/users/components/search-filter-users/search-filter-users.component.scss
  src/users/components/search-filter-users/search-filter-users.component.spec.ts
  src/users/components/search-filter-users/search-filter-users.component.ts
  src/users/components/user-table/user-table-component.spec.ts
  src/users/components/user-table/user-table.component.html
  src/users/components/user-table/user-table.component.ts
  src/users/containers/users/users.component.html
  src/users/containers/users/users.component.scss
  src/users/containers/users/users.component.ts
  src/users/users.module.ts
Labels: ns:xui, prd:xui, destroy, rel:xui-mo-webapp-pr-1217

#1228 updated terraform and azurerm version
  infrastructure/.terraform-version
  infrastructure/provider.tf
Labels: ns:xui, prd:xui, no-changes, rel:xui-mo-webapp-pr-1228

#1220 Feature/release 32.1
  api/caaCaseTypes/index.ts
  api/caaCases/index.ts
  api/models/registrationData.ts
  api/organisation/index.ts
  api/registerOrganisation/index.ts
  charts/xui-mo-webapp/values.preview.template.yaml
  package.json
  src/models/organisation.model.ts
  src/organisation/containers/organisation/organisation.component.html
  src/organisation/containers/organisation/organisation.component.spec.ts
  src/organisation/containers/organisation/organisation.component.ts
  src/organisation/services/organisation.service.ts
  src/organisation/store/effects/organisation.effects.spec.ts
  src/organisation/store/effects/organisation.effects.ts
  src/organisation/utils/index.spec.ts
  src/organisation/utils/index.ts
  src/register-org/components/check-your-answers/check-your-answers.component.html
  src/register-org/components/check-your-answers/check-your-answers.component.spec.ts
  src/register-org/components/check-your-answers/check-your-answers.component.ts
  src/register-org/components/company-house-details/company-house-details.component.spec.ts
  src/register-org/components/company-house-details/company-house-details.component.ts
  test_codecept/e2e/features/app/registerOtherOrgNavigation.feature
  yarn.lock
Labels: ns:xui, prd:xui, destroy, enable_keep_helm, rel:xui-mo-webapp-pr-1220

#1229 GA-95 user details section for manage user
  src/models/organisation.model.ts
  src/users/components/index.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.html
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.spec.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.ts
  src/users/components/standard-user-permissions/standard-user-permissions.component.html
  src/users/components/standard-user-permissions/standard-user-permissions.component.spec.ts
  src/users/components/standard-user-permissions/standard-user-permissions.component.ts
  src/users/components/user-personal-details/user-personal-details.component.html
  src/users/components/user-personal-details/user-personal-details.component.spec.ts
  src/users/components/user-personal-details/user-personal-details.component.ts
  src/users/containers/manage-user/manage-user.component.html
  src/users/containers/manage-user/manage-user.component.ts
  src/users/containers/manage-user/temp-data.ts
  src/users/models/basic-access-types.model.ts
  src/users/models/case-management-permissions.model.ts
  src/users/models/personal-details.model.ts
Labels: ns:xui, prd:xui, destroy, rel:xui-mo-webapp-pr-1229

#1230 GA-96 update profile into accordions
  angular.json
  src/users/components/index.ts
  src/users/components/ogd-cafcass-cy-profile-content/ogd-cafcass-cy-profile-content.component.html
  src/users/components/ogd-cafcass-cy-profile-content/ogd-cafcass-cy-profile-content.component.ts
  src/users/components/ogd-cafcass-en-profile-content/ogd-cafcass-en-profile-content.component.html
  src/users/components/ogd-cafcass-en-profile-content/ogd-cafcass-en-profile-content.component.ts
  src/users/components/ogd-cica-profile-content/ogd-cica-profile-content.component.html
  src/users/components/ogd-cica-profile-content/ogd-cica-profile-content.component.ts
  src/users/components/ogd-dwp-profile-content/ogd-dwp-profile-content.component.html
  src/users/components/ogd-dwp-profile-content/ogd-dwp-profile-content.component.ts
  src/users/components/ogd-hmrc-profile-content/ogd-hmrc-profile-content.component.html
  src/users/components/ogd-hmrc-profile-content/ogd-hmrc-profile-content.component.ts
  src/users/components/ogd-ho-profile-content/ogd-ho-profile-content.component.html
  src/users/components/ogd-ho-profile-content/ogd-ho-profile-content.component.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.html
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.spec.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.ts
  src/users/components/solicitor-profile-content/solicitor-profile-content.component.html
  src/users/components/solicitor-profile-content/solicitor-profile-content.component.scss
  src/users/components/solicitor-profile-content/solicitor-profile-content.component.ts
  src/users/components/standard-user-permissions/standard-user-permissions.component.ts
  src/users/components/user-personal-details/user-personal-details.component.html
  src/users/components/user-personal-details/user-personal-details.component.spec.ts
  src/users/components/user-personal-details/user-personal-details.component.ts
  src/users/containers/index.ts
  src/users/containers/manage-user/manage-user.component.html
  src/users/containers/manage-user/manage-user.component.spec.ts
  src/users/containers/manage-user/manage-user.component.ts
  src/users/containers/ogd-cafcass-cy-profile-content/ogd-cafcass-cy-profile-content.component.html
  src/users/containers/ogd-profile-content/ogd-profile-content.component.html
  src/users/containers/ogd-profile-content/ogd-profile-content.component.ts
  src/users/containers/solicitor-profile-content/solicitor-profile-content.component.html
  src/users/containers/solicitor-profile-content/solicitor-profile-content.component.ts
  src/users/users.module.ts
Labels: ns:xui, prd:xui, destroy, rel:xui-mo-webapp-pr-1230

#1231 Vulnerabilities Fix for User name and password
  Jenkinsfile_CNP
  test/e2e/config/common.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/step_definitions/loginLogout.steps.js
  test/integration/tests/utils/getToken.ts
  test_codecept/e2e/config/common.conf.js
  test_codecept/e2e/config/fullfunctional.conf.js
  test_codecept/e2e/config/smoke.conf.js
  test_codecept/e2e/features/step_definitions/loginLogout.steps.js
  test_codecept/integration/tests/utils/getToken.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1231

#1235 Add refresh user API endpoint
  api/refresh-user/index.ts
  api/routes.ts
  src/user-profile/services/user.service.ts
  src/user-profile/store/effects/user-profile.effects.ts
  src/users/containers/manage-user/manage-user.component.html
  src/users/containers/manage-user/manage-user.component.ts
  src/users/store/actions/user.actions.ts
Labels: ns:xui, prd:xui, destroy, rel:xui-mo-webapp-pr-1235

#1245 Development/ga/ogd 86 update existing api edit user
  package.json
  src/shared/services/logger.service.ts
  src/user-profile/models/editUser.model.ts
  src/user-profile/services/user.service.spec.ts
  src/user-profile/services/user.service.ts
  src/user-profile/store/effects/user-profile.effects.ts
  src/users/components/user-personal-details/user-personal-details.component.spec.ts
  src/users/containers/edit-user-permissions/edit-user-permission.component.ts
  src/users/containers/manage-user/manage-user.component.spec.ts
  src/users/containers/manage-user/manage-user.component.ts
  src/users/containers/users/users.component.html
  src/users/containers/users/users.component.ts
  src/users/containers/utils/user-roles-util.spec.ts
  src/users/containers/utils/user-roles-util.ts
  src/users/store/actions/user.actions.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1245

#1252 GA-130 Update functional tests
  test_codecept/e2e/features/pageObjects/inviteUserPage.js
  test_codecept/e2e/features/pageObjects/manageUserPage.js
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1252

#1248 fix the PBA
  src/organisation/containers/organisation/organisation.component.html
  src/organisation/organisation.routing.ts
  src/register-org/containers/registered-address/registered-address.component.ts
  src/user-profile/store/selectors/auth.selectors.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1248

#1247 GA-61 Map access profile data to AccessType selection checkboxes for existing user
  package.json
  src/users/containers/manage-user/manage-user.component.spec.ts
  src/users/containers/user-details/user-details.component.html
  src/users/containers/user-details/user-details.component.spec.ts
  src/users/containers/user-details/user-details.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1247

#1253 GA-128
  src/users/components/search-filter-users/search-filter-users.component.spec.ts
  src/users/components/search-filter-users/search-filter-users.component.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1253

#1257 GA-76 Update api model mapping
  api/allUserListWithoutRoles/index.ts
  api/user-details/index.ts
  src/karma.conf.js
  src/user-profile/models/editUser.model.ts
  src/user-profile/services/user.service.spec.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.spec.ts
  src/users/components/organisation-access-permissions/organisation-access-permissions.component.ts
  src/users/containers/manage-user/manage-user.component.spec.ts
  src/users/containers/manage-user/manage-user.component.ts
  src/users/containers/user-details/user-details.component.ts
  src/users/containers/utils/user-roles-util.spec.ts
  src/users/containers/utils/user-roles-util.ts
  src/users/models/prd-users.model.ts
  src/users/models/userform.model.ts
  src/users/store/effects/users.effects.spec.ts
  src/users/store/effects/users.effects.ts
  src/users/store/reducers/users.reducer.spec.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1257
