Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2024-09, with the labels that each got.

#1306 Suppress vuln in yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1306

#1301 changed service messages references
  package.json
  src/app/app.constants.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1301

#1307 cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1307

#1308 pipeline fix
  infrastructure/provider.tf
Labels: ns:xui, prd:xui, aat/add-or-update, prod/add-or-update, rel:xui-mo-webapp-pr-1308
