Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2025-03, with the labels that each got.

#1328 WIP:changes a link to a button
  src/users/containers/users/users.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1328

#1329 WIP:adds a version for testing
  package.json
  src/shared/components/hmcts-main-wrapper/hmcts-main-wrapper.component.html
  src/users/containers/users/users.component.html
  test_codecept/e2e/features/pageObjects/inviteUserPage.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1329

#1332 WIP: adds a visaully hidden warning for screen readers
  src/shared/components/hmcts-error-summary/hmcts-error-summary.component.html
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1332

#1323 exui-2655-fortify scan issue
  src/app/app.module.ts
  src/organisation/organisation.module.ts
  src/shared/services/CryptoWrapper.spec.ts
  src/shared/services/cryptoWrapper.ts
  src/shared/services/logger.service.spec.ts
  src/shared/services/logger.service.ts
  src/user-profile/store/effects/user-profile.effects.ts
  src/user-profile/store/effects/user.effects.spec.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1323

#1339 exui-2888 - Change hint text in the Edit User screen
  src/users/components/invite-user-permissions/invite-user-permission.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1339

#1340 CME-384: MO: Update Helm chart
  charts/xui-mo-webapp/Chart.yaml
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1340

#1341 EXUI-2891: Fix Nightly Pipeline Failures
  playwright_tests/helpers/login.ts
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1341

#1348 exui-2969 - fix for crossbrowser build errors
  package.json
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1348
