Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2025-06, with the labels that each got.

#1362 CME-528: replace jitpack
  test/java/build.gradle
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1362

#1368 exui-3212-cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1368

#1369 exui-3230-cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1369
