Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2025-09, with the labels that each got.

#1405 exui 3470 yarn audit issues
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1405

#1402 exui-534 tough-cookie vulnerable fix
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1402

#1406 Tech/ex UI 3423 mermaid CVE issue
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1406

#1374 CME-494 replace appinsights web
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  README.md
  angular.json
  api/configuration/references.ts
  api/interfaces/environment.config.ts
  api/lib/appInsights.spec.ts
  api/lib/appInsights.ts
  api/lib/config/index.spec.ts
  api/lib/config/index.ts
  api/lib/log4jui.spec.ts
  api/monitoring-tools/index.spec.ts
  api/monitoring-tools/index.ts
  api/openRoutes.ts
  charts/xui-mo-webapp/Chart.yaml
  charts/xui-mo-webapp/values.aat.template.yaml
  charts/xui-mo-webapp/values.preview.template.yaml
  charts/xui-mo-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/pacttesting.json
  package.json
  src/organisation/organisation.module.ts
  src/shared/services/appInsightsWrapper.ts
  src/shared/services/monitoring.service.spec.ts
  src/shared/services/monitoring.service.ts
  src/shared/shared.module.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1374

#1394 EXU-3114 tool for pr review process
  .github/workflows/pr-bot.yml
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1394, aat/destroy, prod/destroy
