Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2025-01, with the labels that each got.

#1321 WIP:updates how for label is applied so it works properly
  src/register-org/components/regulator-details/regulator-details.component.html
Labels: ns:xui, prd:xui, enable_keep_helm

#1320 EXUI-2708 - Add playwright tests for use in crossbrowser nightly runs
  .gitignore
  Jenkinsfile_nightly
  package.json
  playwright.config.ts
  playwright_tests/assigned-cases.test.ts
  playwright_tests/config/config.ts
  playwright_tests/helpers/login.ts
  playwright_tests/helpers/navigate.ts
  playwright_tests/helpers/register-org.ts
  playwright_tests/helpers/string.ts
  playwright_tests/login.test.ts
  playwright_tests/register-org.test.ts
  playwright_tests/unassigned-cases.test.ts
  playwright_tests/user-list.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm

#1319 CME-319: Update azurerm
  infrastructure/main.tf
  infrastructure/provider.tf
Labels: ns:xui, prd:xui, aat/add-or-update, prod/no-changes, rel:xui-mo-webapp-pr-1319

#1322 cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1322
