Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2025-02, with the labels that each got.

#1325 CVE
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1325

#1327 EXUI-2820 - update crossbrowser steps
  package.json
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1327

#1331 exui-2823-change contact details
  package.json
  src/app/app.constants.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1331

#1324 exui-2655-xss-defence
  api/allUserList/index.ts
  api/allUserListWithoutRoles/index.ts
  api/caaCases/index.ts
  api/getUserTermsAndConditions/index.ts
  api/lib/util.ts
  api/organisation/index.ts
  api/payments/index.ts
  api/termsAndConditions/index.ts
  api/user-details/index.ts
  api/user/index.ts
  api/userList/index.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1324
