Repository hmcts/rpx-xui-manage-organisations, pull requests merged in 2025-04, with the labels that each got.

#1346 CME:377 - Upgrade Node 20
  .nvmrc
  Dockerfile
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1346

#1350 EXUI-2974 - update fortify version
  package.json
  playwright.config.ts
  playwright_tests/helpers/login.ts
  test/java/build.gradle
  test_codecept/java/.gitignore
  test_codecept/java/build.gradle
  test_codecept/java/config/fortify-client.properties
  test_codecept/java/gradle/wrapper/gradle-wrapper.jar
  test_codecept/java/gradle/wrapper/gradle-wrapper.properties
  test_codecept/java/gradlew
  test_codecept/java/gradlew.bat
  test_codecept/java/settings.gradle
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1350

#1337 WIP:Feature/ongoing accessibility
  package.json
  src/app/store/reducers/app.reducer.spec.ts
  src/app/store/selectors/app.selectors.spec.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/shared/components/hmcts-error-summary/hmcts-error-summary.component.html
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1337

#1345 exui-2832 - update organisationTypes
  api/organisationTypesRouter/index.spec.ts
  api/organisationTypesRouter/mockOrganisationTypes.ts
  api/routes.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1345

#1353 Exui 2915 rc1- Update T and Cs for MyHMCTS in Manage Org
  src/app/components/terms-and-conditions-register-other-org/terms-and-conditions-register-other-org.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1353

#1347 exui-2909 - add new govuk coat of arms to global footer
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/assets/images/govuk-crest.svg
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1347

#1354 CME-379 - Use pre-release node lib
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1354

#1352 exui-2976 - Bump common lib pkg version
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-mo-webapp-pr-1352

#1357 exui-3041-cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1357

#1358 exui-3065-cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-mo-webapp-pr-1358
